<?php
$pathogen_species = ['Absidia corymbifera',
    'Achorion gallinae',
    'Acinetobacter ',
    'Acinetobacter baumannii',
    'Acinetobacter lwoffii',
    'Actinobacillus pleuropneumoniae',
    'Actinomadura ',
    'Actinomyces ',
    'Actinomyces naeslundii',
    'Actinomyces spp.',
    'Actinomyces viscosus',
    'Actinomycetes ',
    'Adenovirus',
    'Adenovirus Human',
    'Aeromonas ',
    'Ajellomyces dermatididis',
    'Alcaligenes faecalis',
    'Alcaligenes spp./Achromobacter spp.',
    'Alcaligenes xylosoxidans',
    'Aleurisma brasiliensis',
    'Allersheria boydii',
    'Arbovirus',
    'Arthroderma ',
    'Ascaris lumbricoides',
    'Aspergillus ',
    'Astrovirus',
    'Bacillus anthracis',
    'Bacillus cereus',
    'Bacillus subtilis',
    'Bacteriodes fragilis',
    'Bartonella quintana',
    'Basidiobolus ',
    'Blastocystis hominis',
    'Blastomyces ',
    'Bordetella pertussis',
    'Borrelia burgdorferi',
    'Borrelia duttoni',
    'Borrelia hermsii',
    'Borrelia recurrentis',
    'Brevundimonas diminuta',
    'Brevundimonas vesicularis',
    'Brucella ',
    'Burkholderia ',
    'Burkholderia cenocepacia',
    'Burkholderia cepacia',
    'Burkholderia mallei',
    'Burkholderia oklahomensis',
    'Burkholderia pseudomallei',
    'Cadophora ',
    'Campylobacter jejuni',
    'Campylobacter jejuni / coli',
    'Campylobacter upsaliensis',
    'Candida albicans',
    'Candida auris',
    'Candida krusei',
    'Candida parapsilosis',
    'Cercospora apii',
    'Chikungunya virus',
    'Chlamydia pneumoniae',
    'Chlamydia psittaci',
    'Chlamydia trachomatis',
    'Chrysosporium ',
    'Citrobacter ',
    'Cladosporium ',
    'Cladothrix asteroids',
    'Clostridium ',
    'Clostridium botulinum',
    'Clostridium difficile',
    'Clostridium difficle',
    'Clostridium perfringens',
    'Clostridium tetani',
    'Coccidioides immitis',
    'Coronavirus',
    'Coronavirus Betacoronavirus',
    'Corynebacterium ',
    'Corynebacterium diphtheriae',
    'Corynebacterium pseudotuberculosis',
    'Corynebacterium ulcerans',
    'Coxiella burnetii',
    'Coxsackievirus',
    'Crimean-Congo haemorrhagic fever virus',
    'Cryptococcus neoformans',
    'Cryptosporidium hominis',
    'Cryptosporidium parvum',
    'Cunninghamella elegans',
    'Cyclospora cayetanensis',
    'Cytomegalovirus',
    'Dematium wernecke',
    'Dengue virus',
    'Dientamoeba fragilis',
    'Discomyces israelii',
    'EAEC ',
    'Ebola virus',
    'Echinococcus ',
    'Echovirus',
    'EHEC ',
    'Emmonsia ',
    'Emmonsiella capsulate',
    'Endomyces geotrichum',
    'Entamoeba dispar',
    'Entamoeba histolytica',
    'Enterobacter aerogenes',
    'Enterobacter cloacae',
    'Enterobacteriaceae spp.',
    'Enterobius vermicularis',
    'Enterococcus faecalis',
    'Enterococcus faecium',
    'Enterococcus hirae',
    'Entomophthora coronate',
    'Epidermophyton',
    'Epidermophyton floccosum',
    'Epstein-Barr virus',
    'Escherichia coli',
    'ETEC ',
    'Filarial worms',
    'Filobasidiella neoformans',
    'Fonsecaea ',
    'Foot-and-mouth disease virus',
    'Francisella tularensis',
    'Fusobacterium nucleatum',
    'Geotrichum candidum',
    'Giardia lamblia',
    'Glenospora khartoumensis',
    'Gymnoascus gypseus',
    'Haemophilus influenzae',
    'Haemophilus parainfluenzae',
    'Hantavirus',
    'Haplosporangium parvum',
    'Has two',
    'Helicobacter bilis',
    'Helicobacter canis',
    'Helicobacter felis',
    'Helicobacter hepaticus',
    'Helicobacter mustelae',
    'Helicobacter pylori',
    'Helminths ',
    'Hepatitis ',
    'Herpes simplex virus',
    'Histoplasma ',
    'Histoplasma capsulatum',
    'Hormiscium dermatididis',
    'Hormodendrum',
    'Human enterovirus',
    'Human immunodeficiency virus',
    'Human metapneumovirus',
    'Human papillomavirus',
    'Hymenolepsis nana',
    'Influenza ',
    'Influenza 1918',
    'Influenza A',
    'Influenza B',
    'Influenza C',
    'Influenza virus',
    'Influenzavirus A',
    'Keratinomyces ',
    'Klebsiella granulomatis',
    'Klebsiella oxytoca',
    'Klebsiella pneumoniae',
    'Lactobacillus casei',
    'Lactobacillus johnsonii',
    'Langeronia soudanense',
    'Lassa virus',
    'Leclercia adecarboxylata',
    'Legionella pneumophila',
    'Leishmania ',
    'Lentivirus ',
    'Lentivirus Human',
    'Leptosphaeria senegalensis',
    'Leptospira interrogans',
    'Leuconostoc pseudomesenteroides',
    'Lichtheimia corymbifera',
    'Listeria monocytogenes',
    'Lobmyces loboi',
    'Loboa loboi',
    'Lobomycosis ',
    'Madurella ',
    'Malassezia furfur',
    'Marburg virus',
    'Measles virus',
    'Micrococcus luteus',
    'Micrococcus pelletieri',
    'Microsporum ',
    'Molluscipoxvirus',
    'Monilia ',
    'Moraxella catarrhalis',
    'Morganella ',
    'Mucor ',
    'Mumps virus',
    'Mycobacterium chimaera',
    'Mycobacterium leprae',
    'Mycobacterium tuberculosis',
    'Mycoplasma gallisepticum',
    'Mycoplasma genitalium',
    'Mycoplasma pneumoniae',
    'Naegleria fowleri',
    'Nannizzia ',
    'Neisseria gonorrhoeae',
    'Neisseria meningitidis',
    'Neotestudina rosatii',
    'Nocardia ',
    'Norovirus',
    'Norovirus norwalk',
    'Oidium albicans',
    'Oospora lactis',
    'Opisthorchis viverrini',
    'Opportunistic pathogen',
    'Orientia tsutsugamushi',
    'Pantoea agglomerans',
    'Paracoccidioides brasiliensis',
    'Paracoccus yeei',
    'Parainfluenza virus',
    'Parvovirus',
    'Pasteurella haemolytica',
    'Pediculus humanus capitis',
    'Pediculus humanus corporis',
    'Petriellidium boydii',
    'Phialophora ',
    'Piedraia hortae',
    'Pityrosporum furfur',
    'Plasmodium ',
    'Plasmodium falciparum',
    'Pneumocystis jiroveci',
    'Poliovirus',
    'Polyomavirus',
    'Polyomavirus ',
    'Polyomavirus Human',
    'Polyomavirus Murine',
    'Prevotella ',
    'Prions ',
    'Propionibacterium granulosum',
    'Propionibacterium sp.',
    'Propionibacterium species',
    'Proteus mirabilis',
    'Proteus vulgaris',
    'Providencia rettgeri',
    'Providencia stuartii',
    'Pseudomonas ',
    'Pseudomonas aeruginosa',
    'Pullularia gougerotii',
    'Pyrenochaeta romeroi',
    'Pythium ',
    'Rabies virus',
    'Ralstonia ',
    'Ramose ',
    'Reovirus ',
    'Respiratory syncytial virus',
    'Respirovirus ',
    'Respirovirus Parainfluenza',
    'Respirovirus Sendai',
    'Rhinosporidium seeberi',
    'Rhinovirus',
    'Ricin toxin',
    'Rickettsia prowazekii',
    'Rickettsia typhi',
    'Ringworm ',
    'Roseomonas gilardii',
    'Rotavirus',
    'Rotavirus ',
    'Rotavirus Bovine',
    'Rotavirus Human',
    'Rotavirus Simian',
    'Rotavirus Unclassified',
    'Rubella virus',
    'Sabouraudites ',
    'Saccharomyces cerevisiae',
    'Salmonella enteritidis',
    'Salmonella paratyphi',
    'Salmonella sp.',
    'Salmonella typhi',
    'Salmonella typhimurium',
    'Sapovirus',
    'Sarcoptes scabiei',
    'Sartorya fumigate',
    'Schistosoma mansoni',
    'Sepedonium ',
    'Serratia marcescens',
    'Shiga toxin',
    'Shiga-like toxin',
    'Shigella dysenteriae',
    'Shigella flexneri',
    'Shigella sonnei',
    'Shigella toxin',
    'Sphingomonas species',
    'Sporothrix schenckii',
    'Sporotrichum ',
    'Staphylococcal enterotoxin-B',
    'Staphylococcus aureus',
    'Staphylococcus capitis',
    'Staphylococcus epidermidis',
    'Staphylococcus haemolyticus',
    'Staphylococcus hominis',
    'Staphylococcus lugdunensis',
    'Staphylococcus pasteuri',
    'Staphylococcus saprophyticus',
    'STEC ',
    'Stenotrophomonas maltophilia',
    'Streptococcus ',
    'Streptococcus gordonii',
    'Streptococcus mitis',
    'Streptococcus pneumoniae',
    'Streptococcus pyogenes',
    'Streptococcus sanguinis',
    'Streptococcus suis',
    'Strongyloides stercoralis',
    'Taenia solium',
    'TBE virus',
    'Tinea ',
    'Torula ',
    'Toxoplasma gondii',
    'Treponema pallidum',
    'Trichinella spiralis',
    'Trichomonas vaginalis',
    'Trichophyton ',
    'Trichuris trichiura',
    'Trypanosoma brucei gambiense',
    'Trypanosoma brucei rhodesiense',
    'Trypanosoma cruzi',
    'UPEC ',
    'UPEC Lab',
    'Usutu virus',
    'Vaccinia virus',
    'Varicella zoster virus',
    'Variola virus',
    'Verotoxin ',
    'Vibrio cholerae',
    'Vibrio damsela',
    'Vibrio furnissii',
    'Vibrio harveyi',
    'VTEC 107/86(serotype',
    'West Nile virus',
    'Yellow fever virus',
    'Yersinia enterocolitica',
    'Yersinia pestis',
    'Yersinia pseudotuberculosis',
    'Zika virus',
    'Zopfia rosatii'];
?>