/*
 Use it if you like it
 @source http://purl.eligrey.com/github/canvas-toBlob.js/blob/master/canvas-toBlob.js  @source http://purl.eligrey.com/github/FileSaver.js/blob/master/FileSaver.js */
(function(){function k(e){var a=[0,0,0],k=function(c,b){var d=e.match(c);null!=d&&(a[b]+=d.length,e=e.replace(c," "))};e=e.replace(/:not\(([^\)]*)\)/g,"     $1 ");e=e.replace(/{[^]*/gm," ");k(q,1);k(A,0);k(y,1);k(p,2);k(I,1);k(l,1);e=e.replace(/[\*\s\+>~]/g," ");e=e.replace(/[#\.]/g," ");k(z,2);return a.join("")}function v(e){var a={opts:e,FRAMERATE:30,MAX_VIRTUAL_PIXELS:3E4,log:function(a){}};1==a.opts.log&&"undefined"!=typeof console&&(a.log=function(a){console.log(a)});a.init=function(c){var b=
0;a.UniqueId=function(){b++;return"canvg"+b};a.Definitions={};a.Styles={};a.StylesSpecificity={};a.Animations=[];a.Images=[];a.ctx=c;a.ViewPort=new function(){this.viewPorts=[];this.Clear=function(){this.viewPorts=[]};this.SetCurrent=function(a,b){this.viewPorts.push({width:a,height:b})};this.RemoveCurrent=function(){this.viewPorts.pop()};this.Current=function(){return this.viewPorts[this.viewPorts.length-1]};this.width=function(){return this.Current().width};this.height=function(){return this.Current().height};
this.ComputeSize=function(a){return null!=a&&"number"==typeof a?a:"x"==a?this.width():"y"==a?this.height():Math.sqrt(Math.pow(this.width(),2)+Math.pow(this.height(),2))/Math.sqrt(2)}}};a.init();a.ImagesLoaded=function(){for(var c=0;c<a.Images.length;c++)if(!a.Images[c].loaded)return!1;return!0};a.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};a.compressSpaces=function(a){return a.replace(/[\s\r\t\n]+/gm," ")};a.ajax=function(a){var b=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");
b.open("GET",a,!1);b.send(null);return b.responseText};a.parseXml=function(a){if("undefined"!=typeof Windows&&"undefined"!=typeof Windows.Data&&"undefined"!=typeof Windows.Data.Xml){var b=new Windows.Data.Xml.Dom.XmlDocument;var d=new Windows.Data.Xml.Dom.XmlLoadSettings;d.prohibitDtd=!1;b.loadXml(a,d);return b}if(window.DOMParser)return(new DOMParser).parseFromString(a,"text/xml");a=a.replace(/<!DOCTYPE svg[^>]*>/,"");b=new ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a);return b};
a.Property=function(a,b){this.name=a;this.value=b};a.Property.prototype.getValue=function(){return this.value};a.Property.prototype.hasValue=function(){return null!=this.value&&""!==this.value};a.Property.prototype.numValue=function(){if(!this.hasValue())return 0;var a=parseFloat(this.value);(this.value+"").match(/%$/)&&(a/=100);return a};a.Property.prototype.valueOrDefault=function(a){return this.hasValue()?this.value:a};a.Property.prototype.numValueOrDefault=function(a){return this.hasValue()?this.numValue():
a};a.Property.prototype.addOpacity=function(c){var b=this.value;if(null!=c.value&&""!=c.value&&"string"==typeof this.value){var d=new RGBColor(this.value);d.ok&&(b="rgba("+d.r+", "+d.g+", "+d.b+", "+c.numValue()+")")}return new a.Property(this.name,b)};a.Property.prototype.getDefinition=function(){var c=this.value.match(/#([^\)'"]+)/);c&&(c=c[1]);c||(c=this.value);return a.Definitions[c]};a.Property.prototype.isUrlDefinition=function(){return 0==this.value.indexOf("url(")};a.Property.prototype.getFillStyleDefinition=
function(c,b){var d=this.getDefinition();if(null!=d&&d.createGradient)return d.createGradient(a.ctx,c,b);if(null!=d&&d.createPattern){if(d.getHrefAttribute().hasValue()){var g=d.attribute("patternTransform"),d=d.getHrefAttribute().getDefinition();g.hasValue()&&(d.attribute("patternTransform",!0).value=g.value)}return d.createPattern(a.ctx,c)}return null};a.Property.prototype.getDPI=function(a){return 96};a.Property.prototype.getEM=function(c){var b=12,d=new a.Property("fontSize",a.Font.Parse(a.ctx.font).fontSize);
d.hasValue()&&(b=d.toPixels(c));return b};a.Property.prototype.getUnits=function(){return(this.value+"").replace(/[0-9\.\-]/g,"")};a.Property.prototype.toPixels=function(c,b){if(!this.hasValue())return 0;var d=this.value+"";if(d.match(/em$/))return this.numValue()*this.getEM(c);if(d.match(/ex$/))return this.numValue()*this.getEM(c)/2;if(d.match(/px$/))return this.numValue();if(d.match(/pt$/))return this.numValue()*this.getDPI(c)*(1/72);if(d.match(/pc$/))return 15*this.numValue();if(d.match(/cm$/))return this.numValue()*
this.getDPI(c)/2.54;if(d.match(/mm$/))return this.numValue()*this.getDPI(c)/25.4;if(d.match(/in$/))return this.numValue()*this.getDPI(c);if(d.match(/%$/))return this.numValue()*a.ViewPort.ComputeSize(c);d=this.numValue();return b&&1>d?d*a.ViewPort.ComputeSize(c):d};a.Property.prototype.toMilliseconds=function(){if(!this.hasValue())return 0;var a=this.value+"";if(a.match(/s$/))return 1E3*this.numValue();a.match(/ms$/);return this.numValue()};a.Property.prototype.toRadians=function(){if(!this.hasValue())return 0;
var a=this.value+"";return a.match(/deg$/)?this.numValue()*(Math.PI/180):a.match(/grad$/)?this.numValue()*(Math.PI/200):a.match(/rad$/)?this.numValue():this.numValue()*(Math.PI/180)};var l={baseline:"alphabetic","before-edge":"top","text-before-edge":"top",middle:"middle",central:"middle","after-edge":"bottom","text-after-edge":"bottom",ideographic:"ideographic",alphabetic:"alphabetic",hanging:"hanging",mathematical:"alphabetic"};a.Property.prototype.toTextBaseline=function(){return this.hasValue()?
l[this.value]:null};a.Font=new function(){this.Styles="normal|italic|oblique|inherit";this.Variants="normal|small-caps|inherit";this.Weights="normal|bold|bolder|lighter|100|200|300|400|500|600|700|800|900|inherit";this.CreateFont=function(b,d,g,c,f,h){h=null!=h?this.Parse(h):this.CreateFont("","","","","",a.ctx.font);return{fontFamily:f||h.fontFamily,fontSize:c||h.fontSize,fontStyle:b||h.fontStyle,fontWeight:g||h.fontWeight,fontVariant:d||h.fontVariant,toString:function(){return[this.fontStyle,this.fontVariant,
this.fontWeight,this.fontSize,this.fontFamily].join(" ")}}};var c=this;this.Parse=function(b){var d={};b=a.trim(a.compressSpaces(b||"")).split(" ");for(var g=!1,r=!1,f=!1,h=!1,w="",e=0;e<b.length;e++)r||-1==c.Styles.indexOf(b[e])?h||-1==c.Variants.indexOf(b[e])?f||-1==c.Weights.indexOf(b[e])?g?"inherit"!=b[e]&&(w+=b[e]):("inherit"!=b[e]&&(d.fontSize=b[e].split("/")[0]),r=h=f=g=!0):("inherit"!=b[e]&&(d.fontWeight=b[e]),r=h=f=!0):("inherit"!=b[e]&&(d.fontVariant=b[e]),r=h=!0):("inherit"!=b[e]&&(d.fontStyle=
b[e]),r=!0);""!=w&&(d.fontFamily=w);return d}};a.ToNumberArray=function(c){c=a.trim(a.compressSpaces((c||"").replace(/,/g," "))).split(" ");for(var b=0;b<c.length;b++)c[b]=parseFloat(c[b]);return c};a.Point=function(a,b){this.x=a;this.y=b};a.Point.prototype.angleTo=function(a){return Math.atan2(a.y-this.y,a.x-this.x)};a.Point.prototype.applyTransform=function(a){var b=this.x*a[1]+this.y*a[3]+a[5];this.x=this.x*a[0]+this.y*a[2]+a[4];this.y=b};a.CreatePoint=function(c){c=a.ToNumberArray(c);return new a.Point(c[0],
c[1])};a.CreatePath=function(c){c=a.ToNumberArray(c);for(var b=[],d=0;d<c.length;d+=2)b.push(new a.Point(c[d],c[d+1]));return b};a.BoundingBox=function(a,b,d,g){this.y2=this.x2=this.y1=this.x1=Number.NaN;this.x=function(){return this.x1};this.y=function(){return this.y1};this.width=function(){return this.x2-this.x1};this.height=function(){return this.y2-this.y1};this.addPoint=function(a,b){if(null!=a){if(isNaN(this.x1)||isNaN(this.x2))this.x2=this.x1=a;a<this.x1&&(this.x1=a);a>this.x2&&(this.x2=a)}if(null!=
b){if(isNaN(this.y1)||isNaN(this.y2))this.y2=this.y1=b;b<this.y1&&(this.y1=b);b>this.y2&&(this.y2=b)}};this.addX=function(a){this.addPoint(a,null)};this.addY=function(a){this.addPoint(null,a)};this.addBoundingBox=function(a){this.addPoint(a.x1,a.y1);this.addPoint(a.x2,a.y2)};this.addQuadraticCurve=function(a,b,d,g,c,e){d=a+2/3*(d-a);g=b+2/3*(g-b);this.addBezierCurve(a,b,d,d+1/3*(c-a),g,g+1/3*(e-b),c,e)};this.addBezierCurve=function(a,b,d,g,c,e,l,k){var f=[a,b],h=[d,g],r=[c,e],w=[l,k];this.addPoint(f[0],
f[1]);this.addPoint(w[0],w[1]);for(i=0;1>=i;i++)a=function(a){return Math.pow(1-a,3)*f[i]+3*Math.pow(1-a,2)*a*h[i]+3*(1-a)*Math.pow(a,2)*r[i]+Math.pow(a,3)*w[i]},b=6*f[i]-12*h[i]+6*r[i],d=-3*f[i]+9*h[i]-9*r[i]+3*w[i],g=3*h[i]-3*f[i],0==d?0!=b&&(b=-g/b,0<b&&1>b&&(0==i&&this.addX(a(b)),1==i&&this.addY(a(b)))):(g=Math.pow(b,2)-4*g*d,0>g||(c=(-b+Math.sqrt(g))/(2*d),0<c&&1>c&&(0==i&&this.addX(a(c)),1==i&&this.addY(a(c))),b=(-b-Math.sqrt(g))/(2*d),0<b&&1>b&&(0==i&&this.addX(a(b)),1==i&&this.addY(a(b)))))};
this.isPointInBox=function(a,b){return this.x1<=a&&a<=this.x2&&this.y1<=b&&b<=this.y2};this.addPoint(a,b);this.addPoint(d,g)};a.Transform=function(c){var b=this;this.Type={};this.Type.translate=function(b){this.p=a.CreatePoint(b);this.apply=function(a){a.translate(this.p.x||0,this.p.y||0)};this.unapply=function(a){a.translate(-1*this.p.x||0,-1*this.p.y||0)};this.applyToPoint=function(a){a.applyTransform([1,0,0,1,this.p.x||0,this.p.y||0])}};this.Type.rotate=function(b){b=a.ToNumberArray(b);this.angle=
new a.Property("angle",b[0]);this.cx=b[1]||0;this.cy=b[2]||0;this.apply=function(a){a.translate(this.cx,this.cy);a.rotate(this.angle.toRadians());a.translate(-this.cx,-this.cy)};this.unapply=function(a){a.translate(this.cx,this.cy);a.rotate(-1*this.angle.toRadians());a.translate(-this.cx,-this.cy)};this.applyToPoint=function(a){var b=this.angle.toRadians();a.applyTransform([1,0,0,1,this.p.x||0,this.p.y||0]);a.applyTransform([Math.cos(b),Math.sin(b),-Math.sin(b),Math.cos(b),0,0]);a.applyTransform([1,
0,0,1,-this.p.x||0,-this.p.y||0])}};this.Type.scale=function(b){this.p=a.CreatePoint(b);this.apply=function(a){a.scale(this.p.x||1,this.p.y||this.p.x||1)};this.unapply=function(a){a.scale(1/this.p.x||1,1/this.p.y||this.p.x||1)};this.applyToPoint=function(a){a.applyTransform([this.p.x||0,0,0,this.p.y||0,0,0])}};this.Type.matrix=function(b){this.m=a.ToNumberArray(b);this.apply=function(a){a.transform(this.m[0],this.m[1],this.m[2],this.m[3],this.m[4],this.m[5])};this.unapply=function(a){var b=this.m[0],
d=this.m[2],g=this.m[4],c=this.m[1],f=this.m[3],h=this.m[5],r=1/(b*(1*f-0*h)-d*(1*c-0*h)+g*(0*c-0*f));a.transform(r*(1*f-0*h),r*(0*h-1*c),r*(0*g-1*d),r*(1*b-0*g),r*(d*h-g*f),r*(g*c-b*h))};this.applyToPoint=function(a){a.applyTransform(this.m)}};this.Type.SkewBase=function(d){this.base=b.Type.matrix;this.base(d);this.angle=new a.Property("angle",d)};this.Type.SkewBase.prototype=new this.Type.matrix;this.Type.skewX=function(a){this.base=b.Type.SkewBase;this.base(a);this.m=[1,0,Math.tan(this.angle.toRadians()),
1,0,0]};this.Type.skewX.prototype=new this.Type.SkewBase;this.Type.skewY=function(a){this.base=b.Type.SkewBase;this.base(a);this.m=[1,Math.tan(this.angle.toRadians()),0,1,0,0]};this.Type.skewY.prototype=new this.Type.SkewBase;this.transforms=[];this.apply=function(a){for(var b=0;b<this.transforms.length;b++)this.transforms[b].apply(a)};this.unapply=function(a){for(var b=this.transforms.length-1;0<=b;b--)this.transforms[b].unapply(a)};this.applyToPoint=function(a){for(var b=0;b<this.transforms.length;b++)this.transforms[b].applyToPoint(a)};
c=a.trim(a.compressSpaces(c)).replace(/\)([a-zA-Z])/g,") $1").replace(/\)(\s?,\s?)/g,") ").split(/\s(?=[a-z])/);for(var d=0;d<c.length;d++){var g=a.trim(c[d].split("(")[0]),r=c[d].split("(")[1].replace(")",""),r=new this.Type[g](r);r.type=g;this.transforms.push(r)}};a.AspectRatio=function(c,b,d,g,r,f,h,w,e,E){b=a.compressSpaces(b);b=b.replace(/^defer\s/,"");var t=b.split(" ")[0]||"xMidYMid";b=b.split(" ")[1]||"meet";var l=d/g,k=r/f,m=Math.min(l,k),n=Math.max(l,k);"meet"==b&&(g*=m,f*=m);"slice"==b&&
(g*=n,f*=n);e=new a.Property("refX",e);E=new a.Property("refY",E);e.hasValue()&&E.hasValue()?c.translate(-m*e.toPixels("x"),-m*E.toPixels("y")):(t.match(/^xMid/)&&("meet"==b&&m==k||"slice"==b&&n==k)&&c.translate(d/2-g/2,0),t.match(/YMid$/)&&("meet"==b&&m==l||"slice"==b&&n==l)&&c.translate(0,r/2-f/2),t.match(/^xMax/)&&("meet"==b&&m==k||"slice"==b&&n==k)&&c.translate(d-g,0),t.match(/YMax$/)&&("meet"==b&&m==l||"slice"==b&&n==l)&&c.translate(0,r-f));"none"==t?c.scale(l,k):"meet"==b?c.scale(m,m):"slice"==
b&&c.scale(n,n);c.translate(null==h?0:-h,null==w?0:-w)};a.Element={};a.EmptyProperty=new a.Property("EMPTY","");a.Element.ElementBase=function(c){this.attributes={};this.styles={};this.stylesSpecificity={};this.children=[];this.attribute=function(b,d){var g=this.attributes[b];if(null!=g)return g;1==d&&(g=new a.Property(b,""),this.attributes[b]=g);return g||a.EmptyProperty};this.getHrefAttribute=function(){for(var b in this.attributes)if("href"==b||b.match(/:href$/))return this.attributes[b];return a.EmptyProperty};
this.style=function(b,d,g){var c=this.styles[b];if(null!=c)return c;var f=this.attribute(b);if(null!=f&&f.hasValue())return this.styles[b]=f;if(1!=g&&(g=this.parent,null!=g&&(g=g.style(b),null!=g&&g.hasValue())))return g;1==d&&(c=new a.Property(b,""),this.styles[b]=c);return c||a.EmptyProperty};this.render=function(a){if("none"!=this.style("display").value&&"hidden"!=this.style("visibility").value){a.save();if(this.attribute("mask").hasValue()){var b=this.attribute("mask").getDefinition();null!=b&&
b.apply(a,this)}else this.style("filter").hasValue()?(b=this.style("filter").getDefinition(),null!=b&&b.apply(a,this)):(this.setContext(a),this.renderChildren(a),this.clearContext(a));a.restore()}};this.setContext=function(a){};this.clearContext=function(a){};this.renderChildren=function(a){for(var b=0;b<this.children.length;b++)this.children[b].render(a)};this.addChild=function(b,d){var g=b;d&&(g=a.CreateElement(b));g.parent=this;"title"!=g.type&&this.children.push(g)};this.addStylesFromStyleDefinition=
function(){for(var b in a.Styles)if("@"!=b[0]&&m(c,b)){var d=a.Styles[b],g=a.StylesSpecificity[b];if(null!=d)for(var r in d){var e=this.stylesSpecificity[r];"undefined"==typeof e&&(e="000");g>e&&(this.styles[r]=d[r],this.stylesSpecificity[r]=g)}}};if(null!=c&&1==c.nodeType){for(var b=0;b<c.attributes.length;b++){var d=c.attributes[b];this.attributes[d.nodeName]=new a.Property(d.nodeName,d.value)}this.addStylesFromStyleDefinition();if(this.attribute("style").hasValue())for(d=this.attribute("style").value.split(";"),
b=0;b<d.length;b++)if(""!=a.trim(d[b])){var g=d[b].split(":"),r=a.trim(g[0]),g=a.trim(g[1]);this.styles[r]=new a.Property(r,g)}this.attribute("id").hasValue()&&null==a.Definitions[this.attribute("id").value]&&(a.Definitions[this.attribute("id").value]=this);for(b=0;b<c.childNodes.length;b++)d=c.childNodes[b],1==d.nodeType&&this.addChild(d,!0),!this.captureTextNodes||3!=d.nodeType&&4!=d.nodeType||""!=a.compressSpaces(d.value||d.text||d.textContent||"")&&this.addChild(new a.Element.tspan(d),!1)}};a.Element.RenderedElementBase=
function(c){this.base=a.Element.ElementBase;this.base(c);this.setContext=function(b){if(this.style("fill").isUrlDefinition()){var d=this.style("fill").getFillStyleDefinition(this,this.style("fill-opacity"));null!=d&&(b.fillStyle=d)}else this.style("fill").hasValue()&&(d=this.style("fill"),"currentColor"==d.value&&(d.value=this.style("color").value),"inherit"!=d.value&&(b.fillStyle="none"==d.value?"rgba(0,0,0,0)":d.value));this.style("fill-opacity").hasValue()&&(d=new a.Property("fill",b.fillStyle),
d=d.addOpacity(this.style("fill-opacity")),b.fillStyle=d.value);this.style("stroke").isUrlDefinition()?(d=this.style("stroke").getFillStyleDefinition(this,this.style("stroke-opacity")),null!=d&&(b.strokeStyle=d)):this.style("stroke").hasValue()&&(d=this.style("stroke"),"currentColor"==d.value&&(d.value=this.style("color").value),"inherit"!=d.value&&(b.strokeStyle="none"==d.value?"rgba(0,0,0,0)":d.value));this.style("stroke-opacity").hasValue()&&(d=new a.Property("stroke",b.strokeStyle),d=d.addOpacity(this.style("stroke-opacity")),
b.strokeStyle=d.value);this.style("stroke-width").hasValue()&&(d=this.style("stroke-width").toPixels(),b.lineWidth=0==d?.001:d);this.style("stroke-linecap").hasValue()&&(b.lineCap=this.style("stroke-linecap").value);this.style("stroke-linejoin").hasValue()&&(b.lineJoin=this.style("stroke-linejoin").value);this.style("stroke-miterlimit").hasValue()&&(b.miterLimit=this.style("stroke-miterlimit").value);this.style("stroke-dasharray").hasValue()&&"none"!=this.style("stroke-dasharray").value&&(d=a.ToNumberArray(this.style("stroke-dasharray").value),
"undefined"!=typeof b.setLineDash?b.setLineDash(d):"undefined"!=typeof b.webkitLineDash?b.webkitLineDash=d:"undefined"==typeof b.mozDash||1==d.length&&0==d[0]||(b.mozDash=d),d=this.style("stroke-dashoffset").numValueOrDefault(1),"undefined"!=typeof b.lineDashOffset?b.lineDashOffset=d:"undefined"!=typeof b.webkitLineDashOffset?b.webkitLineDashOffset=d:"undefined"!=typeof b.mozDashOffset&&(b.mozDashOffset=d));"undefined"!=typeof b.font&&(b.font=a.Font.CreateFont(this.style("font-style").value,this.style("font-variant").value,
this.style("font-weight").value,this.style("font-size").hasValue()?this.style("font-size").toPixels()+"px":"",this.style("font-family").value).toString());this.style("transform",!1,!0).hasValue()&&(new a.Transform(this.style("transform",!1,!0).value)).apply(b);this.attribute("clip-path",!1,!0).hasValue()&&(d=this.attribute("clip-path",!1,!0).getDefinition(),null!=d&&d.apply(b));this.style("opacity").hasValue()&&(b.globalAlpha=this.style("opacity").numValue())}};a.Element.RenderedElementBase.prototype=
new a.Element.ElementBase;a.Element.PathElementBase=function(c){this.base=a.Element.RenderedElementBase;this.base(c);this.path=function(b){null!=b&&b.beginPath();return new a.BoundingBox};this.renderChildren=function(b){this.path(b);a.Mouse.checkPath(this,b);""!=b.fillStyle&&("inherit"!=this.style("fill-rule").valueOrDefault("inherit")?b.fill(this.style("fill-rule").value):b.fill());""!=b.strokeStyle&&b.stroke();var d=this.getMarkers();if(null!=d){if(this.style("marker-start").isUrlDefinition()){var g=
this.style("marker-start").getDefinition();g.render(b,d[0][0],d[0][1])}if(this.style("marker-mid").isUrlDefinition()){g=this.style("marker-mid").getDefinition();for(var c=1;c<d.length-1;c++)g.render(b,d[c][0],d[c][1])}this.style("marker-end").isUrlDefinition()&&(g=this.style("marker-end").getDefinition(),g.render(b,d[d.length-1][0],d[d.length-1][1]))}};this.getBoundingBox=function(){return this.path()};this.getMarkers=function(){return null}};a.Element.PathElementBase.prototype=new a.Element.RenderedElementBase;
a.Element.svg=function(c){this.base=a.Element.RenderedElementBase;this.base(c);this.baseClearContext=this.clearContext;this.clearContext=function(b){this.baseClearContext(b);a.ViewPort.RemoveCurrent()};this.baseSetContext=this.setContext;this.setContext=function(b){b.strokeStyle="rgba(0,0,0,0)";b.lineCap="butt";b.lineJoin="miter";b.miterLimit=4;"undefined"!=typeof b.font&&"undefined"!=typeof window.getComputedStyle&&(b.font=window.getComputedStyle(b.canvas).getPropertyValue("font"));this.baseSetContext(b);
this.attribute("x").hasValue()||(this.attribute("x",!0).value=0);this.attribute("y").hasValue()||(this.attribute("y",!0).value=0);b.translate(this.attribute("x").toPixels("x"),this.attribute("y").toPixels("y"));var d=a.ViewPort.width(),g=a.ViewPort.height();this.attribute("width").hasValue()||(this.attribute("width",!0).value="100%");this.attribute("height").hasValue()||(this.attribute("height",!0).value="100%");if("undefined"==typeof this.root){var d=this.attribute("width").toPixels("x"),g=this.attribute("height").toPixels("y"),
c=0,f=0;this.attribute("refX").hasValue()&&this.attribute("refY").hasValue()&&(c=-this.attribute("refX").toPixels("x"),f=-this.attribute("refY").toPixels("y"));"visible"!=this.attribute("overflow").valueOrDefault("hidden")&&(b.beginPath(),b.moveTo(c,f),b.lineTo(d,f),b.lineTo(d,g),b.lineTo(c,g),b.closePath(),b.clip())}a.ViewPort.SetCurrent(d,g);if(this.attribute("viewBox").hasValue()){var c=a.ToNumberArray(this.attribute("viewBox").value),f=c[0],h=c[1],d=c[2],g=c[3];a.AspectRatio(b,this.attribute("preserveAspectRatio").value,
a.ViewPort.width(),d,a.ViewPort.height(),g,f,h,this.attribute("refX").value,this.attribute("refY").value);a.ViewPort.RemoveCurrent();a.ViewPort.SetCurrent(c[2],c[3])}}};a.Element.svg.prototype=new a.Element.RenderedElementBase;a.Element.rect=function(c){this.base=a.Element.PathElementBase;this.base(c);this.path=function(b){var d=this.attribute("x").toPixels("x"),g=this.attribute("y").toPixels("y"),c=this.attribute("width").toPixels("x"),f=this.attribute("height").toPixels("y"),h=this.attribute("rx").toPixels("x"),
e=this.attribute("ry").toPixels("y");this.attribute("rx").hasValue()&&!this.attribute("ry").hasValue()&&(e=h);this.attribute("ry").hasValue()&&!this.attribute("rx").hasValue()&&(h=e);h=Math.min(h,c/2);e=Math.min(e,f/2);null!=b&&(b.beginPath(),b.moveTo(d+h,g),b.lineTo(d+c-h,g),b.quadraticCurveTo(d+c,g,d+c,g+e),b.lineTo(d+c,g+f-e),b.quadraticCurveTo(d+c,g+f,d+c-h,g+f),b.lineTo(d+h,g+f),b.quadraticCurveTo(d,g+f,d,g+f-e),b.lineTo(d,g+e),b.quadraticCurveTo(d,g,d+h,g),b.closePath());return new a.BoundingBox(d,
g,d+c,g+f)}};a.Element.rect.prototype=new a.Element.PathElementBase;a.Element.circle=function(c){this.base=a.Element.PathElementBase;this.base(c);this.path=function(b){var d=this.attribute("cx").toPixels("x"),g=this.attribute("cy").toPixels("y"),c=this.attribute("r").toPixels();null!=b&&(b.beginPath(),b.arc(d,g,c,0,2*Math.PI,!0),b.closePath());return new a.BoundingBox(d-c,g-c,d+c,g+c)}};a.Element.circle.prototype=new a.Element.PathElementBase;a.Element.ellipse=function(c){this.base=a.Element.PathElementBase;
this.base(c);this.path=function(b){var d=(Math.sqrt(2)-1)/3*4,g=this.attribute("rx").toPixels("x"),c=this.attribute("ry").toPixels("y"),f=this.attribute("cx").toPixels("x"),h=this.attribute("cy").toPixels("y");null!=b&&(b.beginPath(),b.moveTo(f,h-c),b.bezierCurveTo(f+d*g,h-c,f+g,h-d*c,f+g,h),b.bezierCurveTo(f+g,h+d*c,f+d*g,h+c,f,h+c),b.bezierCurveTo(f-d*g,h+c,f-g,h+d*c,f-g,h),b.bezierCurveTo(f-g,h-d*c,f-d*g,h-c,f,h-c),b.closePath());return new a.BoundingBox(f-g,h-c,f+g,h+c)}};a.Element.ellipse.prototype=
new a.Element.PathElementBase;a.Element.line=function(c){this.base=a.Element.PathElementBase;this.base(c);this.getPoints=function(){return[new a.Point(this.attribute("x1").toPixels("x"),this.attribute("y1").toPixels("y")),new a.Point(this.attribute("x2").toPixels("x"),this.attribute("y2").toPixels("y"))]};this.path=function(b){var d=this.getPoints();null!=b&&(b.beginPath(),b.moveTo(d[0].x,d[0].y),b.lineTo(d[1].x,d[1].y));return new a.BoundingBox(d[0].x,d[0].y,d[1].x,d[1].y)};this.getMarkers=function(){var a=
this.getPoints(),d=a[0].angleTo(a[1]);return[[a[0],d],[a[1],d]]}};a.Element.line.prototype=new a.Element.PathElementBase;a.Element.polyline=function(c){this.base=a.Element.PathElementBase;this.base(c);this.points=a.CreatePath(this.attribute("points").value);this.path=function(b){var d=new a.BoundingBox(this.points[0].x,this.points[0].y);null!=b&&(b.beginPath(),b.moveTo(this.points[0].x,this.points[0].y));for(var g=1;g<this.points.length;g++)d.addPoint(this.points[g].x,this.points[g].y),null!=b&&b.lineTo(this.points[g].x,
this.points[g].y);return d};this.getMarkers=function(){for(var a=[],d=0;d<this.points.length-1;d++)a.push([this.points[d],this.points[d].angleTo(this.points[d+1])]);a.push([this.points[this.points.length-1],a[a.length-1][1]]);return a}};a.Element.polyline.prototype=new a.Element.PathElementBase;a.Element.polygon=function(c){this.base=a.Element.polyline;this.base(c);this.basePath=this.path;this.path=function(a){var b=this.basePath(a);null!=a&&(a.lineTo(this.points[0].x,this.points[0].y),a.closePath());
return b}};a.Element.polygon.prototype=new a.Element.polyline;a.Element.path=function(c){this.base=a.Element.PathElementBase;this.base(c);c=this.attribute("d").value;c=c.replace(/,/gm," ");for(var b=0;2>b;b++)c=c.replace(/([MmZzLlHhVvCcSsQqTtAa])([^\s])/gm,"$1 $2");c=c.replace(/([^\s])([MmZzLlHhVvCcSsQqTtAa])/gm,"$1 $2");c=c.replace(/([0-9])([+\-])/gm,"$1 $2");for(b=0;2>b;b++)c=c.replace(/(\.[0-9]*)(\.)/gm,"$1 $2");c=c.replace(/([Aa](\s+[0-9]+){3})\s+([01])\s*([01])/gm,"$1 $3 $4 ");c=a.compressSpaces(c);
c=a.trim(c);this.PathParser=new function(b){this.tokens=b.split(" ");this.reset=function(){this.i=-1;this.previousCommand=this.command="";this.start=new a.Point(0,0);this.control=new a.Point(0,0);this.current=new a.Point(0,0);this.points=[];this.angles=[]};this.isEnd=function(){return this.i>=this.tokens.length-1};this.isCommandOrEnd=function(){return this.isEnd()?!0:null!=this.tokens[this.i+1].match(/^[A-Za-z]$/)};this.isRelativeCommand=function(){switch(this.command){case "m":case "l":case "h":case "v":case "c":case "s":case "q":case "t":case "a":case "z":return!0}return!1};
this.getToken=function(){this.i++;return this.tokens[this.i]};this.getScalar=function(){return parseFloat(this.getToken())};this.nextCommand=function(){this.previousCommand=this.command;this.command=this.getToken()};this.getPoint=function(){var b=new a.Point(this.getScalar(),this.getScalar());return this.makeAbsolute(b)};this.getAsControlPoint=function(){var a=this.getPoint();return this.control=a};this.getAsCurrentPoint=function(){var a=this.getPoint();return this.current=a};this.getReflectedControlPoint=
function(){return"c"!=this.previousCommand.toLowerCase()&&"s"!=this.previousCommand.toLowerCase()&&"q"!=this.previousCommand.toLowerCase()&&"t"!=this.previousCommand.toLowerCase()?this.current:new a.Point(2*this.current.x-this.control.x,2*this.current.y-this.control.y)};this.makeAbsolute=function(a){this.isRelativeCommand()&&(a.x+=this.current.x,a.y+=this.current.y);return a};this.addMarker=function(a,b,d){null!=d&&0<this.angles.length&&null==this.angles[this.angles.length-1]&&(this.angles[this.angles.length-
1]=this.points[this.points.length-1].angleTo(d));this.addMarkerAngle(a,null==b?null:b.angleTo(a))};this.addMarkerAngle=function(a,b){this.points.push(a);this.angles.push(b)};this.getMarkerPoints=function(){return this.points};this.getMarkerAngles=function(){for(var a=0;a<this.angles.length;a++)if(null==this.angles[a])for(var b=a+1;b<this.angles.length;b++)if(null!=this.angles[b]){this.angles[a]=this.angles[b];break}return this.angles}}(c);this.path=function(b){var d=this.PathParser;d.reset();var c=
new a.BoundingBox;for(null!=b&&b.beginPath();!d.isEnd();)switch(d.nextCommand(),d.command){case "M":case "m":var f=d.getAsCurrentPoint();d.addMarker(f);c.addPoint(f.x,f.y);null!=b&&b.moveTo(f.x,f.y);for(d.start=d.current;!d.isCommandOrEnd();)f=d.getAsCurrentPoint(),d.addMarker(f,d.start),c.addPoint(f.x,f.y),null!=b&&b.lineTo(f.x,f.y);break;case "L":case "l":for(;!d.isCommandOrEnd();){var h=d.current;f=d.getAsCurrentPoint();d.addMarker(f,h);c.addPoint(f.x,f.y);null!=b&&b.lineTo(f.x,f.y)}break;case "H":case "h":for(;!d.isCommandOrEnd();)f=
new a.Point((d.isRelativeCommand()?d.current.x:0)+d.getScalar(),d.current.y),d.addMarker(f,d.current),d.current=f,c.addPoint(d.current.x,d.current.y),null!=b&&b.lineTo(d.current.x,d.current.y);break;case "V":case "v":for(;!d.isCommandOrEnd();)f=new a.Point(d.current.x,(d.isRelativeCommand()?d.current.y:0)+d.getScalar()),d.addMarker(f,d.current),d.current=f,c.addPoint(d.current.x,d.current.y),null!=b&&b.lineTo(d.current.x,d.current.y);break;case "C":case "c":for(;!d.isCommandOrEnd();){var e=d.current;
var t=d.getPoint();h=d.getAsControlPoint();f=d.getAsCurrentPoint();d.addMarker(f,h,t);c.addBezierCurve(e.x,e.y,t.x,t.y,h.x,h.y,f.x,f.y);null!=b&&b.bezierCurveTo(t.x,t.y,h.x,h.y,f.x,f.y)}break;case "S":case "s":for(;!d.isCommandOrEnd();)e=d.current,t=d.getReflectedControlPoint(),h=d.getAsControlPoint(),f=d.getAsCurrentPoint(),d.addMarker(f,h,t),c.addBezierCurve(e.x,e.y,t.x,t.y,h.x,h.y,f.x,f.y),null!=b&&b.bezierCurveTo(t.x,t.y,h.x,h.y,f.x,f.y);break;case "Q":case "q":for(;!d.isCommandOrEnd();)e=d.current,
h=d.getAsControlPoint(),f=d.getAsCurrentPoint(),d.addMarker(f,h,h),c.addQuadraticCurve(e.x,e.y,h.x,h.y,f.x,f.y),null!=b&&b.quadraticCurveTo(h.x,h.y,f.x,f.y);break;case "T":case "t":for(;!d.isCommandOrEnd();)e=d.current,h=d.getReflectedControlPoint(),d.control=h,f=d.getAsCurrentPoint(),d.addMarker(f,h,h),c.addQuadraticCurve(e.x,e.y,h.x,h.y,f.x,f.y),null!=b&&b.quadraticCurveTo(h.x,h.y,f.x,f.y);break;case "A":case "a":for(;!d.isCommandOrEnd();){e=d.current;var l=d.getScalar(),k=d.getScalar();h=d.getScalar()*
(Math.PI/180);var m=d.getScalar();t=d.getScalar();f=d.getAsCurrentPoint();var p=new a.Point(Math.cos(h)*(e.x-f.x)/2+Math.sin(h)*(e.y-f.y)/2,-Math.sin(h)*(e.x-f.x)/2+Math.cos(h)*(e.y-f.y)/2),u=Math.pow(p.x,2)/Math.pow(l,2)+Math.pow(p.y,2)/Math.pow(k,2);1<u&&(l*=Math.sqrt(u),k*=Math.sqrt(u));m=(m==t?-1:1)*Math.sqrt((Math.pow(l,2)*Math.pow(k,2)-Math.pow(l,2)*Math.pow(p.y,2)-Math.pow(k,2)*Math.pow(p.x,2))/(Math.pow(l,2)*Math.pow(p.y,2)+Math.pow(k,2)*Math.pow(p.x,2)));isNaN(m)&&(m=0);var n=new a.Point(m*
l*p.y/k,m*-k*p.x/l);e=new a.Point((e.x+f.x)/2+Math.cos(h)*n.x-Math.sin(h)*n.y,(e.y+f.y)/2+Math.sin(h)*n.x+Math.cos(h)*n.y);var q=function(a,b){return(a[0]*b[0]+a[1]*b[1])/(Math.sqrt(Math.pow(a[0],2)+Math.pow(a[1],2))*Math.sqrt(Math.pow(b[0],2)+Math.pow(b[1],2)))};var v=function(a,b){return(a[0]*b[1]<a[1]*b[0]?-1:1)*Math.acos(q(a,b))},m=v([1,0],[(p.x-n.x)/l,(p.y-n.y)/k]),u=[(p.x-n.x)/l,(p.y-n.y)/k],n=[(-p.x-n.x)/l,(-p.y-n.y)/k],p=v(u,n);-1>=q(u,n)&&(p=Math.PI);1<=q(u,n)&&(p=0);u=1-t?1:-1;n=m+p/2*u;
v=new a.Point(e.x+l*Math.cos(n),e.y+k*Math.sin(n));d.addMarkerAngle(v,n-u*Math.PI/2);d.addMarkerAngle(f,n-u*Math.PI);c.addPoint(f.x,f.y);null!=b&&(q=l>k?l:k,f=l>k?1:l/k,l=l>k?k/l:1,b.translate(e.x,e.y),b.rotate(h),b.scale(f,l),b.arc(0,0,q,m,m+p,1-t),b.scale(1/f,1/l),b.rotate(-h),b.translate(-e.x,-e.y))}break;case "Z":case "z":null!=b&&b.closePath(),d.current=d.start}return c};this.getMarkers=function(){for(var a=this.PathParser.getMarkerPoints(),b=this.PathParser.getMarkerAngles(),c=[],f=0;f<a.length;f++)c.push([a[f],
b[f]]);return c}};a.Element.path.prototype=new a.Element.PathElementBase;a.Element.pattern=function(c){this.base=a.Element.ElementBase;this.base(c);this.createPattern=function(b,d){var c=this.attribute("width").toPixels("x",!0),e=this.attribute("height").toPixels("y",!0),f=new a.Element.svg;f.attributes.viewBox=new a.Property("viewBox",this.attribute("viewBox").value);f.attributes.width=new a.Property("width",c+"px");f.attributes.height=new a.Property("height",e+"px");f.attributes.transform=new a.Property("transform",
this.attribute("patternTransform").value);f.children=this.children;var h=document.createElement("canvas");h.width=c;h.height=e;c=h.getContext("2d");this.attribute("x").hasValue()&&this.attribute("y").hasValue()&&c.translate(this.attribute("x").toPixels("x",!0),this.attribute("y").toPixels("y",!0));for(e=-1;1>=e;e++)for(var w=-1;1>=w;w++)c.save(),f.attributes.x=new a.Property("x",e*h.width),f.attributes.y=new a.Property("y",w*h.height),f.render(c),c.restore();return b.createPattern(h,"repeat")}};a.Element.pattern.prototype=
new a.Element.ElementBase;a.Element.marker=function(c){this.base=a.Element.ElementBase;this.base(c);this.baseRender=this.render;this.render=function(b,d,c){b.translate(d.x,d.y);"auto"==this.attribute("orient").valueOrDefault("auto")&&b.rotate(c);"strokeWidth"==this.attribute("markerUnits").valueOrDefault("strokeWidth")&&b.scale(b.lineWidth,b.lineWidth);b.save();var g=new a.Element.svg;g.attributes.viewBox=new a.Property("viewBox",this.attribute("viewBox").value);g.attributes.refX=new a.Property("refX",
this.attribute("refX").value);g.attributes.refY=new a.Property("refY",this.attribute("refY").value);g.attributes.width=new a.Property("width",this.attribute("markerWidth").value);g.attributes.height=new a.Property("height",this.attribute("markerHeight").value);g.attributes.fill=new a.Property("fill",this.attribute("fill").valueOrDefault("black"));g.attributes.stroke=new a.Property("stroke",this.attribute("stroke").valueOrDefault("none"));g.children=this.children;g.render(b);b.restore();"strokeWidth"==
this.attribute("markerUnits").valueOrDefault("strokeWidth")&&b.scale(1/b.lineWidth,1/b.lineWidth);"auto"==this.attribute("orient").valueOrDefault("auto")&&b.rotate(-c);b.translate(-d.x,-d.y)}};a.Element.marker.prototype=new a.Element.ElementBase;a.Element.defs=function(c){this.base=a.Element.ElementBase;this.base(c);this.render=function(a){}};a.Element.defs.prototype=new a.Element.ElementBase;a.Element.GradientBase=function(c){this.base=a.Element.ElementBase;this.base(c);this.stops=[];for(c=0;c<this.children.length;c++){var b=
this.children[c];"stop"==b.type&&this.stops.push(b)}this.getGradient=function(){};this.gradientUnits=function(){return this.attribute("gradientUnits").valueOrDefault("objectBoundingBox")};this.attributesToInherit=["gradientUnits"];this.inheritStopContainer=function(a){for(var b=0;b<this.attributesToInherit.length;b++){var d=this.attributesToInherit[b];!this.attribute(d).hasValue()&&a.attribute(d).hasValue()&&(this.attribute(d,!0).value=a.attribute(d).value)}};this.createGradient=function(b,c,e){var d=
this;this.getHrefAttribute().hasValue()&&(d=this.getHrefAttribute().getDefinition(),this.inheritStopContainer(d));var g=function(b){return e.hasValue()?(new a.Property("color",b)).addOpacity(e).value:b};b=this.getGradient(b,c);if(null==b)return g(d.stops[d.stops.length-1].color);for(c=0;c<d.stops.length;c++)b.addColorStop(d.stops[c].offset,g(d.stops[c].color));return this.attribute("gradientTransform").hasValue()?(d=a.ViewPort.viewPorts[0],g=new a.Element.rect,g.attributes.x=new a.Property("x",-a.MAX_VIRTUAL_PIXELS/
3),g.attributes.y=new a.Property("y",-a.MAX_VIRTUAL_PIXELS/3),g.attributes.width=new a.Property("width",a.MAX_VIRTUAL_PIXELS),g.attributes.height=new a.Property("height",a.MAX_VIRTUAL_PIXELS),c=new a.Element.g,c.attributes.transform=new a.Property("transform",this.attribute("gradientTransform").value),c.children=[g],g=new a.Element.svg,g.attributes.x=new a.Property("x",0),g.attributes.y=new a.Property("y",0),g.attributes.width=new a.Property("width",d.width),g.attributes.height=new a.Property("height",
d.height),g.children=[c],c=document.createElement("canvas"),c.width=d.width,c.height=d.height,d=c.getContext("2d"),d.fillStyle=b,g.render(d),d.createPattern(c,"no-repeat")):b}};a.Element.GradientBase.prototype=new a.Element.ElementBase;a.Element.linearGradient=function(c){this.base=a.Element.GradientBase;this.base(c);this.attributesToInherit.push("x1");this.attributesToInherit.push("y1");this.attributesToInherit.push("x2");this.attributesToInherit.push("y2");this.getGradient=function(a,d){var b="objectBoundingBox"==
this.gradientUnits()?d.getBoundingBox():null;this.attribute("x1").hasValue()||this.attribute("y1").hasValue()||this.attribute("x2").hasValue()||this.attribute("y2").hasValue()||(this.attribute("x1",!0).value=0,this.attribute("y1",!0).value=0,this.attribute("x2",!0).value=1,this.attribute("y2",!0).value=0);var c="objectBoundingBox"==this.gradientUnits()?b.x()+b.width()*this.attribute("x1").numValue():this.attribute("x1").toPixels("x"),f="objectBoundingBox"==this.gradientUnits()?b.y()+b.height()*this.attribute("y1").numValue():
this.attribute("y1").toPixels("y"),e="objectBoundingBox"==this.gradientUnits()?b.x()+b.width()*this.attribute("x2").numValue():this.attribute("x2").toPixels("x"),b="objectBoundingBox"==this.gradientUnits()?b.y()+b.height()*this.attribute("y2").numValue():this.attribute("y2").toPixels("y");return c==e&&f==b?null:a.createLinearGradient(c,f,e,b)}};a.Element.linearGradient.prototype=new a.Element.GradientBase;a.Element.radialGradient=function(c){this.base=a.Element.GradientBase;this.base(c);this.attributesToInherit.push("cx");
this.attributesToInherit.push("cy");this.attributesToInherit.push("r");this.attributesToInherit.push("fx");this.attributesToInherit.push("fy");this.getGradient=function(a,d){var b=d.getBoundingBox();this.attribute("cx").hasValue()||(this.attribute("cx",!0).value="50%");this.attribute("cy").hasValue()||(this.attribute("cy",!0).value="50%");this.attribute("r").hasValue()||(this.attribute("r",!0).value="50%");var c="objectBoundingBox"==this.gradientUnits()?b.x()+b.width()*this.attribute("cx").numValue():
this.attribute("cx").toPixels("x"),f="objectBoundingBox"==this.gradientUnits()?b.y()+b.height()*this.attribute("cy").numValue():this.attribute("cy").toPixels("y"),e=c,w=f;this.attribute("fx").hasValue()&&(e="objectBoundingBox"==this.gradientUnits()?b.x()+b.width()*this.attribute("fx").numValue():this.attribute("fx").toPixels("x"));this.attribute("fy").hasValue()&&(w="objectBoundingBox"==this.gradientUnits()?b.y()+b.height()*this.attribute("fy").numValue():this.attribute("fy").toPixels("y"));b="objectBoundingBox"==
this.gradientUnits()?(b.width()+b.height())/2*this.attribute("r").numValue():this.attribute("r").toPixels();return a.createRadialGradient(e,w,0,c,f,b)}};a.Element.radialGradient.prototype=new a.Element.GradientBase;a.Element.stop=function(c){this.base=a.Element.ElementBase;this.base(c);this.offset=this.attribute("offset").numValue();0>this.offset&&(this.offset=0);1<this.offset&&(this.offset=1);c=this.style("stop-color",!0);""===c.value&&(c.value="#000");this.style("stop-opacity").hasValue()&&(c=c.addOpacity(this.style("stop-opacity")));
this.color=c.value};a.Element.stop.prototype=new a.Element.ElementBase;a.Element.AnimateBase=function(c){this.base=a.Element.ElementBase;this.base(c);a.Animations.push(this);this.duration=0;this.begin=this.attribute("begin").toMilliseconds();this.maxDuration=this.begin+this.attribute("dur").toMilliseconds();this.getProperty=function(){var a=this.attribute("attributeType").value,d=this.attribute("attributeName").value;return"CSS"==a?this.parent.style(d,!0):this.parent.attribute(d,!0)};this.initialValue=
null;this.initialUnits="";this.removed=!1;this.calcValue=function(){return""};this.update=function(a){null==this.initialValue&&(this.initialValue=this.getProperty().value,this.initialUnits=this.getProperty().getUnits());if(this.duration>this.maxDuration){if("indefinite"==this.attribute("repeatCount").value||"indefinite"==this.attribute("repeatDur").value)this.duration=0;else if("freeze"==this.attribute("fill").valueOrDefault("remove")&&!this.frozen)this.frozen=!0,this.parent.animationFrozen=!0,this.parent.animationFrozenValue=
this.getProperty().value;else if("remove"==this.attribute("fill").valueOrDefault("remove")&&!this.removed)return this.removed=!0,this.getProperty().value=this.parent.animationFrozen?this.parent.animationFrozenValue:this.initialValue,!0;return!1}this.duration+=a;a=!1;this.begin<this.duration&&(a=this.calcValue(),this.attribute("type").hasValue()&&(a=this.attribute("type").value+"("+a+")"),this.getProperty().value=a,a=!0);return a};this.from=this.attribute("from");this.to=this.attribute("to");this.values=
this.attribute("values");this.values.hasValue()&&(this.values.value=this.values.value.split(";"));this.progress=function(){var b={progress:(this.duration-this.begin)/(this.maxDuration-this.begin)};if(this.values.hasValue()){var d=b.progress*(this.values.value.length-1),c=Math.floor(d),e=Math.ceil(d);b.from=new a.Property("from",parseFloat(this.values.value[c]));b.to=new a.Property("to",parseFloat(this.values.value[e]));b.progress=(d-c)/(e-c)}else b.from=this.from,b.to=this.to;return b}};a.Element.AnimateBase.prototype=
new a.Element.ElementBase;a.Element.animate=function(c){this.base=a.Element.AnimateBase;this.base(c);this.calcValue=function(){var a=this.progress();return a.from.numValue()+(a.to.numValue()-a.from.numValue())*a.progress+this.initialUnits}};a.Element.animate.prototype=new a.Element.AnimateBase;a.Element.animateColor=function(c){this.base=a.Element.AnimateBase;this.base(c);this.calcValue=function(){var a=this.progress(),d=new RGBColor(a.from.value),c=new RGBColor(a.to.value);if(d.ok&&c.ok){var e=d.g+
(c.g-d.g)*a.progress,f=d.b+(c.b-d.b)*a.progress;return"rgb("+parseInt(d.r+(c.r-d.r)*a.progress,10)+","+parseInt(e,10)+","+parseInt(f,10)+")"}return this.attribute("from").value}};a.Element.animateColor.prototype=new a.Element.AnimateBase;a.Element.animateTransform=function(c){this.base=a.Element.AnimateBase;this.base(c);this.calcValue=function(){for(var b=this.progress(),d=a.ToNumberArray(b.from.value),c=a.ToNumberArray(b.to.value),e="",f=0;f<d.length;f++)e+=d[f]+(c[f]-d[f])*b.progress+" ";return e}};
a.Element.animateTransform.prototype=new a.Element.animate;a.Element.font=function(c){this.base=a.Element.ElementBase;this.base(c);this.horizAdvX=this.attribute("horiz-adv-x").numValue();this.isArabic=this.isRTL=!1;this.missingGlyph=this.fontFace=null;this.glyphs=[];for(c=0;c<this.children.length;c++){var b=this.children[c];"font-face"==b.type?(this.fontFace=b,b.style("font-family").hasValue()&&(a.Definitions[b.style("font-family").value]=this)):"missing-glyph"==b.type?this.missingGlyph=b:"glyph"==
b.type&&(""!=b.arabicForm?(this.isArabic=this.isRTL=!0,"undefined"==typeof this.glyphs[b.unicode]&&(this.glyphs[b.unicode]=[]),this.glyphs[b.unicode][b.arabicForm]=b):this.glyphs[b.unicode]=b)}};a.Element.font.prototype=new a.Element.ElementBase;a.Element.fontface=function(c){this.base=a.Element.ElementBase;this.base(c);this.ascent=this.attribute("ascent").value;this.descent=this.attribute("descent").value;this.unitsPerEm=this.attribute("units-per-em").numValue()};a.Element.fontface.prototype=new a.Element.ElementBase;
a.Element.missingglyph=function(c){this.base=a.Element.path;this.base(c);this.horizAdvX=0};a.Element.missingglyph.prototype=new a.Element.path;a.Element.glyph=function(c){this.base=a.Element.path;this.base(c);this.horizAdvX=this.attribute("horiz-adv-x").numValue();this.unicode=this.attribute("unicode").value;this.arabicForm=this.attribute("arabic-form").value};a.Element.glyph.prototype=new a.Element.path;a.Element.text=function(c){this.captureTextNodes=!0;this.base=a.Element.RenderedElementBase;this.base(c);
this.baseSetContext=this.setContext;this.setContext=function(a){this.baseSetContext(a);var b=this.style("dominant-baseline").toTextBaseline();null==b&&(b=this.style("alignment-baseline").toTextBaseline());null!=b&&(a.textBaseline=b)};this.getBoundingBox=function(){var b=this.attribute("x").toPixels("x"),d=this.attribute("y").toPixels("y"),c=this.parent.style("font-size").numValueOrDefault(a.Font.Parse(a.ctx.font).fontSize);return new a.BoundingBox(b,d-c,b+Math.floor(2*c/3)*this.children[0].getText().length,
d)};this.renderChildren=function(a){this.x=this.attribute("x").toPixels("x");this.y=this.attribute("y").toPixels("y");this.attribute("dx").hasValue()&&(this.x+=this.attribute("dx").toPixels("x"));this.attribute("dy").hasValue()&&(this.y+=this.attribute("dy").toPixels("y"));this.x+=this.getAnchorDelta(a,this,0);for(var b=0;b<this.children.length;b++)this.renderChild(a,this,b)};this.getAnchorDelta=function(a,d,c){var b=this.style("text-anchor").valueOrDefault("start");if("start"!=b){for(var g=0,e=c;e<
d.children.length;e++){var w=d.children[e];if(e>c&&w.attribute("x").hasValue())break;g+=w.measureTextRecursive(a)}return-1*("end"==b?g:g/2)}return 0};this.renderChild=function(a,d,c){var b=d.children[c];b.attribute("x").hasValue()?(b.x=b.attribute("x").toPixels("x")+d.getAnchorDelta(a,d,c),b.attribute("dx").hasValue()&&(b.x+=b.attribute("dx").toPixels("x"))):(b.attribute("dx").hasValue()&&(d.x+=b.attribute("dx").toPixels("x")),b.x=d.x);d.x=b.x+b.measureText(a);b.attribute("y").hasValue()?(b.y=b.attribute("y").toPixels("y"),
b.attribute("dy").hasValue()&&(b.y+=b.attribute("dy").toPixels("y"))):(b.attribute("dy").hasValue()&&(d.y+=b.attribute("dy").toPixels("y")),b.y=d.y);d.y=b.y;b.render(a);for(c=0;c<b.children.length;c++)d.renderChild(a,b,c)}};a.Element.text.prototype=new a.Element.RenderedElementBase;a.Element.TextElementBase=function(c){this.base=a.Element.RenderedElementBase;this.base(c);this.getGlyph=function(a,d,c){var b=d[c],g=null;if(a.isArabic){var e="isolated";(0==c||" "==d[c-1])&&c<d.length-2&&" "!=d[c+1]&&
(e="terminal");0<c&&" "!=d[c-1]&&c<d.length-2&&" "!=d[c+1]&&(e="medial");0<c&&" "!=d[c-1]&&(c==d.length-1||" "==d[c+1])&&(e="initial");"undefined"!=typeof a.glyphs[b]&&(g=a.glyphs[b][e],null==g&&"glyph"==a.glyphs[b].type&&(g=a.glyphs[b]))}else g=a.glyphs[b];null==g&&(g=a.missingGlyph);return g};this.renderChildren=function(b){var d=this.parent.style("font-family").getDefinition();if(null!=d){var c=this.parent.style("font-size").numValueOrDefault(a.Font.Parse(a.ctx.font).fontSize),e=this.parent.style("font-style").valueOrDefault(a.Font.Parse(a.ctx.font).fontStyle),
f=this.getText();d.isRTL&&(f=f.split("").reverse().join(""));for(var h=a.ToNumberArray(this.parent.attribute("dx").value),w=0;w<f.length;w++){var l=this.getGlyph(d,f,w),k=c/d.fontFace.unitsPerEm;b.translate(this.x,this.y);b.scale(k,-k);var m=b.lineWidth;b.lineWidth=b.lineWidth*d.fontFace.unitsPerEm/c;"italic"==e&&b.transform(1,0,.4,1,0,0);l.render(b);"italic"==e&&b.transform(1,0,-.4,1,0,0);b.lineWidth=m;b.scale(1/k,-1/k);b.translate(-this.x,-this.y);this.x+=c*(l.horizAdvX||d.horizAdvX)/d.fontFace.unitsPerEm;
"undefined"==typeof h[w]||isNaN(h[w])||(this.x+=h[w])}}else""!=b.fillStyle&&b.fillText(a.compressSpaces(this.getText()),this.x,this.y),""!=b.strokeStyle&&b.strokeText(a.compressSpaces(this.getText()),this.x,this.y)};this.getText=function(){};this.measureTextRecursive=function(a){for(var b=this.measureText(a),c=0;c<this.children.length;c++)b+=this.children[c].measureTextRecursive(a);return b};this.measureText=function(b){var d=this.parent.style("font-family").getDefinition();if(null!=d){b=this.parent.style("font-size").numValueOrDefault(a.Font.Parse(a.ctx.font).fontSize);
var c=0,e=this.getText();d.isRTL&&(e=e.split("").reverse().join(""));for(var f=a.ToNumberArray(this.parent.attribute("dx").value),h=0;h<e.length;h++){var w=this.getGlyph(d,e,h),c=c+(w.horizAdvX||d.horizAdvX)*b/d.fontFace.unitsPerEm;"undefined"==typeof f[h]||isNaN(f[h])||(c+=f[h])}return c}d=a.compressSpaces(this.getText());if(!b.measureText)return 10*d.length;b.save();this.setContext(b);d=b.measureText(d).width;b.restore();return d}};a.Element.TextElementBase.prototype=new a.Element.RenderedElementBase;
a.Element.tspan=function(c){this.captureTextNodes=!0;this.base=a.Element.TextElementBase;this.base(c);this.text=a.compressSpaces(c.value||c.text||c.textContent||"");this.getText=function(){return 0<this.children.length?"":this.text}};a.Element.tspan.prototype=new a.Element.TextElementBase;a.Element.tref=function(c){this.base=a.Element.TextElementBase;this.base(c);this.getText=function(){var a=this.getHrefAttribute().getDefinition();if(null!=a)return a.children[0].getText()}};a.Element.tref.prototype=
new a.Element.TextElementBase;a.Element.a=function(c){this.base=a.Element.TextElementBase;this.base(c);this.hasText=0<c.childNodes.length;for(var b=0;b<c.childNodes.length;b++)3!=c.childNodes[b].nodeType&&(this.hasText=!1);this.text=this.hasText?c.childNodes[0].value:"";this.getText=function(){return this.text};this.baseRenderChildren=this.renderChildren;this.renderChildren=function(b){if(this.hasText){this.baseRenderChildren(b);var d=new a.Property("fontSize",a.Font.Parse(a.ctx.font).fontSize);a.Mouse.checkBoundingBox(this,
new a.BoundingBox(this.x,this.y-d.toPixels("y"),this.x+this.measureText(b),this.y))}else 0<this.children.length&&(d=new a.Element.g,d.children=this.children,d.parent=this,d.render(b))};this.onclick=function(){window.open(this.getHrefAttribute().value)};this.onmousemove=function(){a.ctx.canvas.style.cursor="pointer"}};a.Element.a.prototype=new a.Element.TextElementBase;a.Element.image=function(c){this.base=a.Element.RenderedElementBase;this.base(c);var b=this.getHrefAttribute().value;if(""!=b){var d=
b.match(/\.svg$/);a.Images.push(this);this.loaded=!1;if(d)this.img=a.ajax(b),this.loaded=!0;else{this.img=document.createElement("img");1==a.opts.useCORS&&(this.img.crossOrigin="Anonymous");var g=this;this.img.onload=function(){g.loaded=!0};this.img.onerror=function(){a.log('ERROR: image "'+b+'" not found');g.loaded=!0};this.img.src=b}this.renderChildren=function(b){var c=this.attribute("x").toPixels("x"),g=this.attribute("y").toPixels("y"),e=this.attribute("width").toPixels("x"),l=this.attribute("height").toPixels("y");
0!=e&&0!=l&&(b.save(),d?b.drawSvg(this.img,c,g,e,l):(b.translate(c,g),a.AspectRatio(b,this.attribute("preserveAspectRatio").value,e,this.img.width,l,this.img.height,0,0),b.drawImage(this.img,0,0)),b.restore())};this.getBoundingBox=function(){var b=this.attribute("x").toPixels("x"),d=this.attribute("y").toPixels("y"),c=this.attribute("width").toPixels("x"),g=this.attribute("height").toPixels("y");return new a.BoundingBox(b,d,b+c,d+g)}}};a.Element.image.prototype=new a.Element.RenderedElementBase;a.Element.g=
function(c){this.base=a.Element.RenderedElementBase;this.base(c);this.getBoundingBox=function(){for(var b=new a.BoundingBox,d=0;d<this.children.length;d++)b.addBoundingBox(this.children[d].getBoundingBox());return b}};a.Element.g.prototype=new a.Element.RenderedElementBase;a.Element.symbol=function(c){this.base=a.Element.RenderedElementBase;this.base(c);this.render=function(a){}};a.Element.symbol.prototype=new a.Element.RenderedElementBase;a.Element.style=function(c){this.base=a.Element.ElementBase;
this.base(c);for(var b="",d=0;d<c.childNodes.length;d++)b+=c.childNodes[d].data;b=b.replace(/(\/\*([^*]|[\r\n]|(\*+([^*\/]|[\r\n])))*\*+\/)|(^[\s]*\/\/.*)/gm,"");b=a.compressSpaces(b);c=b.split("}");for(d=0;d<c.length;d++)if(""!=a.trim(c[d]))for(var g=c[d].split("{"),b=g[0].split(","),g=g[1].split(";"),e=0;e<b.length;e++){var f=a.trim(b[e]);if(""!=f){for(var h={},l=0;l<g.length;l++){var t=g[l].indexOf(":"),m=g[l].substr(0,t),t=g[l].substr(t+1,g[l].length-t);null!=m&&null!=t&&(h[a.trim(m)]=new a.Property(a.trim(m),
a.trim(t)))}a.Styles[f]=h;a.StylesSpecificity[f]=k(f);if("@font-face"==f)for(f=h["font-family"].value.replace(/"/g,""),h=h.src.value.split(","),l=0;l<h.length;l++)if(0<h[l].indexOf('format("svg")'))for(m=h[l].indexOf("url"),t=h[l].indexOf(")",m),m=h[l].substr(m+5,t-m-6),m=a.parseXml(a.ajax(m)).getElementsByTagName("font"),t=0;t<m.length;t++){var p=a.CreateElement(m[t]);a.Definitions[f]=p}}}};a.Element.style.prototype=new a.Element.ElementBase;a.Element.use=function(c){this.base=a.Element.RenderedElementBase;
this.base(c);this.baseSetContext=this.setContext;this.setContext=function(a){this.baseSetContext(a);this.attribute("x").hasValue()&&a.translate(this.attribute("x").toPixels("x"),0);this.attribute("y").hasValue()&&a.translate(0,this.attribute("y").toPixels("y"))};var b=this.getHrefAttribute().getDefinition();this.path=function(a){null!=b&&b.path(a)};this.getBoundingBox=function(){if(null!=b)return b.getBoundingBox()};this.renderChildren=function(d){if(null!=b){var c=b;"symbol"==b.type&&(c=new a.Element.svg,
c.type="svg",c.attributes.viewBox=new a.Property("viewBox",b.attribute("viewBox").value),c.attributes.preserveAspectRatio=new a.Property("preserveAspectRatio",b.attribute("preserveAspectRatio").value),c.attributes.overflow=new a.Property("overflow",b.attribute("overflow").value),c.children=b.children);"svg"==c.type&&(this.attribute("width").hasValue()&&(c.attributes.width=new a.Property("width",this.attribute("width").value)),this.attribute("height").hasValue()&&(c.attributes.height=new a.Property("height",
this.attribute("height").value)));var e=c.parent;c.parent=null;c.render(d);c.parent=e}}};a.Element.use.prototype=new a.Element.RenderedElementBase;a.Element.mask=function(c){this.base=a.Element.ElementBase;this.base(c);this.apply=function(b,c){var d=this.attribute("x").toPixels("x");var e=this.attribute("y").toPixels("y");var f=this.attribute("width").toPixels("x");var h=this.attribute("height").toPixels("y");if(0==f&&0==h){h=new a.BoundingBox;for(f=0;f<this.children.length;f++)h.addBoundingBox(this.children[f].getBoundingBox());
d=Math.floor(h.x1);e=Math.floor(h.y1);f=Math.floor(h.width());h=Math.floor(h.height())}var l=c.attribute("mask").value;c.attribute("mask").value="";var k=document.createElement("canvas");k.width=d+f;k.height=e+h;var m=k.getContext("2d");this.renderChildren(m);var p=document.createElement("canvas");p.width=d+f;p.height=e+h;var u=p.getContext("2d");c.render(u);u.globalCompositeOperation="destination-in";u.fillStyle=m.createPattern(k,"no-repeat");u.fillRect(0,0,d+f,e+h);b.fillStyle=u.createPattern(p,
"no-repeat");b.fillRect(0,0,d+f,e+h);c.attribute("mask").value=l};this.render=function(a){}};a.Element.mask.prototype=new a.Element.ElementBase;a.Element.clipPath=function(c){this.base=a.Element.ElementBase;this.base(c);this.apply=function(b){var c=CanvasRenderingContext2D.prototype.beginPath;CanvasRenderingContext2D.prototype.beginPath=function(){};var e=CanvasRenderingContext2D.prototype.closePath;CanvasRenderingContext2D.prototype.closePath=function(){};c.call(b);for(var l=0;l<this.children.length;l++){var f=
this.children[l];if("undefined"!=typeof f.path){var h=null;f.style("transform",!1,!0).hasValue()&&(h=new a.Transform(f.style("transform",!1,!0).value),h.apply(b));f.path(b);CanvasRenderingContext2D.prototype.closePath=e;h&&h.unapply(b)}}e.call(b);b.clip();CanvasRenderingContext2D.prototype.beginPath=c;CanvasRenderingContext2D.prototype.closePath=e};this.render=function(a){}};a.Element.clipPath.prototype=new a.Element.ElementBase;a.Element.filter=function(c){this.base=a.Element.ElementBase;this.base(c);
this.apply=function(a,c){var b=c.getBoundingBox(),d=Math.floor(b.x1),e=Math.floor(b.y1),h=Math.floor(b.width()),b=Math.floor(b.height()),l=c.style("filter").value;c.style("filter").value="";for(var k=0,m=0,p=0;p<this.children.length;p++)var u=this.children[p].extraFilterDistance||0,k=Math.max(k,u),m=Math.max(m,u);u=document.createElement("canvas");u.width=h+2*k;u.height=b+2*m;var q=u.getContext("2d");q.translate(-d+k,-e+m);c.render(q);for(p=0;p<this.children.length;p++)"function"===typeof this.children[p].apply&&
this.children[p].apply(q,0,0,h+2*k,b+2*m);a.drawImage(u,0,0,h+2*k,b+2*m,d-k,e-m,h+2*k,b+2*m);c.style("filter",!0).value=l};this.render=function(a){}};a.Element.filter.prototype=new a.Element.ElementBase;a.Element.feMorphology=function(c){this.base=a.Element.ElementBase;this.base(c);this.apply=function(a,c,e,l,f){}};a.Element.feMorphology.prototype=new a.Element.ElementBase;a.Element.feComposite=function(c){this.base=a.Element.ElementBase;this.base(c);this.apply=function(a,c,e,l,f){}};a.Element.feComposite.prototype=
new a.Element.ElementBase;a.Element.feColorMatrix=function(c){function b(a,b){var c=d[a];return c*(0>c?b-255:b)}this.base=a.Element.ElementBase;this.base(c);var d=a.ToNumberArray(this.attribute("values").value);switch(this.attribute("type").valueOrDefault("matrix")){case "saturate":c=d[0];d=[.213+.787*c,.715-.715*c,.072-.072*c,0,0,.213-.213*c,.715+.285*c,.072-.072*c,0,0,.213-.213*c,.715-.715*c,.072+.928*c,0,0,0,0,0,1,0,0,0,0,0,1];break;case "hueRotate":var e=d[0]*Math.PI/180;c=function(a,b,c){return a+
Math.cos(e)*b+Math.sin(e)*c};d=[c(.213,.787,-.213),c(.715,-.715,-.715),c(.072,-.072,.928),0,0,c(.213,-.213,.143),c(.715,.285,.14),c(.072,-.072,-.283),0,0,c(.213,-.213,-.787),c(.715,-.715,.715),c(.072,.928,.072),0,0,0,0,0,1,0,0,0,0,0,1];break;case "luminanceToAlpha":d=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,.2125,.7154,.0721,0,0,0,0,0,0,1]}this.apply=function(a,c,d,e,g){var f=a.getImageData(0,0,e,g);for(d=0;d<g;d++)for(c=0;c<e;c++){var h=f.data[d*e*4+4*c+0],l=f.data[d*e*4+4*c+1],k=f.data[d*e*4+4*c+2],m=f.data[d*
e*4+4*c+3],p=b(0,h)+b(1,l)+b(2,k)+b(3,m)+b(4,1);f.data[d*e*4+4*c+0]=p;p=b(5,h)+b(6,l)+b(7,k)+b(8,m)+b(9,1);f.data[d*e*4+4*c+1]=p;p=b(10,h)+b(11,l)+b(12,k)+b(13,m)+b(14,1);f.data[d*e*4+4*c+2]=p;h=b(15,h)+b(16,l)+b(17,k)+b(18,m)+b(19,1);f.data[d*e*4+4*c+3]=h}a.clearRect(0,0,e,g);a.putImageData(f,0,0)}};a.Element.feColorMatrix.prototype=new a.Element.ElementBase;a.Element.feGaussianBlur=function(c){this.base=a.Element.ElementBase;this.base(c);this.extraFilterDistance=this.blurRadius=Math.floor(this.attribute("stdDeviation").numValue());
this.apply=function(b,c,e,l,f){"undefined"==typeof stackBlurCanvasRGBA?a.log("ERROR: StackBlur.js must be included for blur to work"):(b.canvas.id=a.UniqueId(),b.canvas.style.display="none",document.body.appendChild(b.canvas),stackBlurCanvasRGBA(b.canvas.id,c,e,l,f,this.blurRadius),document.body.removeChild(b.canvas))}};a.Element.feGaussianBlur.prototype=new a.Element.ElementBase;a.Element.title=function(a){};a.Element.title.prototype=new a.Element.ElementBase;a.Element.desc=function(a){};a.Element.desc.prototype=
new a.Element.ElementBase;a.Element.MISSING=function(c){a.log("ERROR: Element '"+c.nodeName+"' not yet implemented.")};a.Element.MISSING.prototype=new a.Element.ElementBase;a.CreateElement=function(c){var b=c.nodeName.replace(/^[^:]+:/,""),b=b.replace(/\-/g,""),b="undefined"!=typeof a.Element[b]?new a.Element[b](c):new a.Element.MISSING(c);b.type=c.nodeName;return b};a.load=function(c,b){a.loadXml(c,a.ajax(b))};a.loadXml=function(c,b){a.loadXmlDoc(c,a.parseXml(b))};a.loadXmlDoc=function(c,b){a.init(c);
var d=function(a){for(var b=c.canvas;b;)a.x-=b.offsetLeft,a.y-=b.offsetTop,b=b.offsetParent;window.scrollX&&(a.x+=window.scrollX);window.scrollY&&(a.y+=window.scrollY);return a};1!=a.opts.ignoreMouse&&(c.canvas.onclick=function(b){b=d(new a.Point(null!=b?b.clientX:event.clientX,null!=b?b.clientY:event.clientY));a.Mouse.onclick(b.x,b.y)},c.canvas.onmousemove=function(b){b=d(new a.Point(null!=b?b.clientX:event.clientX,null!=b?b.clientY:event.clientY));a.Mouse.onmousemove(b.x,b.y)});var e=a.CreateElement(b.documentElement);
e.root=!0;e.addStylesFromStyleDefinition();var l=!0,f=function(){a.ViewPort.Clear();c.canvas.parentNode&&a.ViewPort.SetCurrent(c.canvas.parentNode.clientWidth,c.canvas.parentNode.clientHeight);1!=a.opts.ignoreDimensions&&(e.style("width").hasValue()&&(c.canvas.width=e.style("width").toPixels("x"),c.canvas.style.width=c.canvas.width+"px"),e.style("height").hasValue()&&(c.canvas.height=e.style("height").toPixels("y"),c.canvas.style.height=c.canvas.height+"px"));var d=c.canvas.clientWidth||c.canvas.width,
f=c.canvas.clientHeight||c.canvas.height;1==a.opts.ignoreDimensions&&e.style("width").hasValue()&&e.style("height").hasValue()&&(d=e.style("width").toPixels("x"),f=e.style("height").toPixels("y"));a.ViewPort.SetCurrent(d,f);null!=a.opts.offsetX&&(e.attribute("x",!0).value=a.opts.offsetX);null!=a.opts.offsetY&&(e.attribute("y",!0).value=a.opts.offsetY);if(null!=a.opts.scaleWidth||null!=a.opts.scaleHeight){var g=null,h=null,k=a.ToNumberArray(e.attribute("viewBox").value);null!=a.opts.scaleWidth&&(e.attribute("width").hasValue()?
g=e.attribute("width").toPixels("x")/a.opts.scaleWidth:isNaN(k[2])||(g=k[2]/a.opts.scaleWidth));null!=a.opts.scaleHeight&&(e.attribute("height").hasValue()?h=e.attribute("height").toPixels("y")/a.opts.scaleHeight:isNaN(k[3])||(h=k[3]/a.opts.scaleHeight));null==g&&(g=h);null==h&&(h=g);e.attribute("width",!0).value=a.opts.scaleWidth;e.attribute("height",!0).value=a.opts.scaleHeight;e.style("transform",!0,!0).value+=" scale("+1/g+","+1/h+")"}1!=a.opts.ignoreClear&&c.clearRect(0,0,d,f);e.render(c);l&&
(l=!1,"function"==typeof a.opts.renderCallback&&a.opts.renderCallback(b))},h=!0;a.ImagesLoaded()&&(h=!1,f());a.intervalID=setInterval(function(){var b=!1;h&&a.ImagesLoaded()&&(h=!1,b=!0);1!=a.opts.ignoreMouse&&(b|=a.Mouse.hasEvents());if(1!=a.opts.ignoreAnimation)for(var c=0;c<a.Animations.length;c++)b|=a.Animations[c].update(1E3/a.FRAMERATE);"function"==typeof a.opts.forceRedraw&&1==a.opts.forceRedraw()&&(b=!0);b&&(f(),a.Mouse.runEvents())},1E3/a.FRAMERATE)};a.stop=function(){a.intervalID&&clearInterval(a.intervalID)};
a.Mouse=new function(){this.events=[];this.hasEvents=function(){return 0!=this.events.length};this.onclick=function(a,b){this.events.push({type:"onclick",x:a,y:b,run:function(a){if(a.onclick)a.onclick()}})};this.onmousemove=function(a,b){this.events.push({type:"onmousemove",x:a,y:b,run:function(a){if(a.onmousemove)a.onmousemove()}})};this.eventElements=[];this.checkPath=function(a,b){for(var c=0;c<this.events.length;c++){var e=this.events[c];b.isPointInPath&&b.isPointInPath(e.x,e.y)&&(this.eventElements[c]=
a)}};this.checkBoundingBox=function(a,b){for(var c=0;c<this.events.length;c++){var e=this.events[c];b.isPointInBox(e.x,e.y)&&(this.eventElements[c]=a)}};this.runEvents=function(){a.ctx.canvas.style.cursor="";for(var c=0;c<this.events.length;c++)for(var b=this.events[c],d=this.eventElements[c];d;)b.run(d),d=d.parent;this.events=[];this.eventElements=[]}};return a}this.canvg=function(e,a,l){if(null==e&&null==a&&null==l)for(a=document.querySelectorAll("svg"),e=0;e<a.length;e++){l=a[e];var c=document.createElement("canvas");
c.width=l.clientWidth;c.height=l.clientHeight;l.parentNode.insertBefore(c,l);l.parentNode.removeChild(l);var b=document.createElement("div");b.appendChild(l);canvg(c,b.innerHTML)}else{"string"==typeof e&&(e=document.getElementById(e));null!=e.svg&&e.svg.stop();l=v(l||{});if(1!=e.childNodes.length||"OBJECT"!=e.childNodes[0].nodeName)e.svg=l;e=e.getContext("2d");"undefined"!=typeof a.documentElement?l.loadXmlDoc(e,a):"<"==a.substr(0,1)?l.loadXml(e,a):l.load(e,a)}};if("undefined"!=typeof Element.prototype.matches)var m=
function(e,a){return e.matches(a)};else if("undefined"!=typeof Element.prototype.webkitMatchesSelector)m=function(e,a){return e.webkitMatchesSelector(a)};else if("undefined"!=typeof Element.prototype.mozMatchesSelector)m=function(e,a){return e.mozMatchesSelector(a)};else if("undefined"!=typeof Element.prototype.msMatchesSelector)m=function(e,a){return e.msMatchesSelector(a)};else if("undefined"!=typeof Element.prototype.oMatchesSelector)m=function(e,a){return e.oMatchesSelector(a)};else{if("function"===
typeof jQuery||"function"===typeof Zepto)m=function(e,a){return $(e).is(a)};"undefined"===typeof m&&(m=Sizzle.matchesSelector)}var q=/(\[[^\]]+\])/g,A=/(#[^\s\+>~\.\[:]+)/g,y=/(\.[^\s\+>~\.\[:]+)/g,p=/(::[^\s\+>~\.\[:]+|:first-line|:first-letter|:before|:after)/gi,I=/(:[\w-]+\([^\)]*\))/gi,l=/(:[^\s\+>~\.\[:]+)/g,z=/([^\s\+>~\.\[:]+)/g})();
"undefined"!=typeof CanvasRenderingContext2D&&(CanvasRenderingContext2D.prototype.drawSvg=function(k,v,m,q,A){canvg(this.canvas,k,{ignoreMouse:!0,ignoreAnimation:!0,ignoreDimensions:!0,ignoreClear:!0,offsetX:v,offsetY:m,scaleWidth:q,scaleHeight:A})});
function RGBColor(k){this.ok=!1;"#"==k.charAt(0)&&(k=k.substr(1,6));k=k.replace(/ /g,"");k=k.toLowerCase();var v={aliceblue:"f0f8ff",antiquewhite:"faebd7",aqua:"00ffff",aquamarine:"7fffd4",azure:"f0ffff",beige:"f5f5dc",bisque:"ffe4c4",black:"000000",blanchedalmond:"ffebcd",blue:"0000ff",blueviolet:"8a2be2",brown:"a52a2a",burlywood:"deb887",cadetblue:"5f9ea0",chartreuse:"7fff00",chocolate:"d2691e",coral:"ff7f50",cornflowerblue:"6495ed",cornsilk:"fff8dc",crimson:"dc143c",cyan:"00ffff",darkblue:"00008b",
darkcyan:"008b8b",darkgoldenrod:"b8860b",darkgray:"a9a9a9",darkgreen:"006400",darkkhaki:"bdb76b",darkmagenta:"8b008b",darkolivegreen:"556b2f",darkorange:"ff8c00",darkorchid:"9932cc",darkred:"8b0000",darksalmon:"e9967a",darkseagreen:"8fbc8f",darkslateblue:"483d8b",darkslategray:"2f4f4f",darkturquoise:"00ced1",darkviolet:"9400d3",deeppink:"ff1493",deepskyblue:"00bfff",dimgray:"696969",dodgerblue:"1e90ff",feldspar:"d19275",firebrick:"b22222",floralwhite:"fffaf0",forestgreen:"228b22",fuchsia:"ff00ff",
gainsboro:"dcdcdc",ghostwhite:"f8f8ff",gold:"ffd700",goldenrod:"daa520",gray:"808080",green:"008000",greenyellow:"adff2f",honeydew:"f0fff0",hotpink:"ff69b4",indianred:"cd5c5c",indigo:"4b0082",ivory:"fffff0",khaki:"f0e68c",lavender:"e6e6fa",lavenderblush:"fff0f5",lawngreen:"7cfc00",lemonchiffon:"fffacd",lightblue:"add8e6",lightcoral:"f08080",lightcyan:"e0ffff",lightgoldenrodyellow:"fafad2",lightgrey:"d3d3d3",lightgreen:"90ee90",lightpink:"ffb6c1",lightsalmon:"ffa07a",lightseagreen:"20b2aa",lightskyblue:"87cefa",
lightslateblue:"8470ff",lightslategray:"778899",lightsteelblue:"b0c4de",lightyellow:"ffffe0",lime:"00ff00",limegreen:"32cd32",linen:"faf0e6",magenta:"ff00ff",maroon:"800000",mediumaquamarine:"66cdaa",mediumblue:"0000cd",mediumorchid:"ba55d3",mediumpurple:"9370d8",mediumseagreen:"3cb371",mediumslateblue:"7b68ee",mediumspringgreen:"00fa9a",mediumturquoise:"48d1cc",mediumvioletred:"c71585",midnightblue:"191970",mintcream:"f5fffa",mistyrose:"ffe4e1",moccasin:"ffe4b5",navajowhite:"ffdead",navy:"000080",
oldlace:"fdf5e6",olive:"808000",olivedrab:"6b8e23",orange:"ffa500",orangered:"ff4500",orchid:"da70d6",palegoldenrod:"eee8aa",palegreen:"98fb98",paleturquoise:"afeeee",palevioletred:"d87093",papayawhip:"ffefd5",peachpuff:"ffdab9",peru:"cd853f",pink:"ffc0cb",plum:"dda0dd",powderblue:"b0e0e6",purple:"800080",red:"ff0000",rosybrown:"bc8f8f",royalblue:"4169e1",saddlebrown:"8b4513",salmon:"fa8072",sandybrown:"f4a460",seagreen:"2e8b57",seashell:"fff5ee",sienna:"a0522d",silver:"c0c0c0",skyblue:"87ceeb",slateblue:"6a5acd",
slategray:"708090",snow:"fffafa",springgreen:"00ff7f",steelblue:"4682b4",tan:"d2b48c",teal:"008080",thistle:"d8bfd8",tomato:"ff6347",turquoise:"40e0d0",violet:"ee82ee",violetred:"d02090",wheat:"f5deb3",white:"ffffff",whitesmoke:"f5f5f5",yellow:"ffff00",yellowgreen:"9acd32"},m;for(m in v)k==m&&(k=v[m]);var q=[{re:/^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,example:["rgb(123, 234, 45)","rgb(255,234,245)"],process:function(k){return[parseInt(k[1]),parseInt(k[2]),parseInt(k[3])]}},{re:/^(\w{2})(\w{2})(\w{2})$/,
example:["#00ff00","336699"],process:function(k){return[parseInt(k[1],16),parseInt(k[2],16),parseInt(k[3],16)]}},{re:/^(\w{1})(\w{1})(\w{1})$/,example:["#fb0","f0f"],process:function(k){return[parseInt(k[1]+k[1],16),parseInt(k[2]+k[2],16),parseInt(k[3]+k[3],16)]}}];for(m=0;m<q.length;m++){var A=q[m].process,y=q[m].re.exec(k);y&&(channels=A(y),this.r=channels[0],this.g=channels[1],this.b=channels[2],this.ok=!0)}this.r=0>this.r||isNaN(this.r)?0:255<this.r?255:this.r;this.g=0>this.g||isNaN(this.g)?0:
255<this.g?255:this.g;this.b=0>this.b||isNaN(this.b)?0:255<this.b?255:this.b;this.toRGB=function(){return"rgb("+this.r+", "+this.g+", "+this.b+")"};this.toHex=function(){var k=this.r.toString(16),m=this.g.toString(16),l=this.b.toString(16);1==k.length&&(k="0"+k);1==m.length&&(m="0"+m);1==l.length&&(l="0"+l);return"#"+k+m+l};this.getHelpXML=function(){for(var k=[],m=0;m<q.length;m++)for(var l=q[m].example,z=0;z<l.length;z++)k[k.length]=l[z];for(var e in v)k[k.length]=e;l=document.createElement("ul");
l.setAttribute("id","rgbcolor-examples");for(m=0;m<k.length;m++)try{var a=document.createElement("li"),u=new RGBColor(k[m]),c=document.createElement("div");c.style.cssText="margin: 3px; border: 1px solid black; background:"+u.toHex()+"; color:"+u.toHex();c.appendChild(document.createTextNode("test"));var b=document.createTextNode(" "+k[m]+" -> "+u.toRGB()+" -> "+u.toHex());a.appendChild(c);a.appendChild(b);l.appendChild(a)}catch(d){}return l}}
var mul_table=[512,512,456,512,328,456,335,512,405,328,271,456,388,335,292,512,454,405,364,328,298,271,496,456,420,388,360,335,312,292,273,512,482,454,428,405,383,364,345,328,312,298,284,271,259,496,475,456,437,420,404,388,374,360,347,335,323,312,302,292,282,273,265,512,497,482,468,454,441,428,417,405,394,383,373,364,354,345,337,328,320,312,305,298,291,284,278,271,265,259,507,496,485,475,465,456,446,437,428,420,412,404,396,388,381,374,367,360,354,347,341,335,329,323,318,312,307,302,297,292,287,282,
278,273,269,265,261,512,505,497,489,482,475,468,461,454,447,441,435,428,422,417,411,405,399,394,389,383,378,373,368,364,359,354,350,345,341,337,332,328,324,320,316,312,309,305,301,298,294,291,287,284,281,278,274,271,268,265,262,259,257,507,501,496,491,485,480,475,470,465,460,456,451,446,442,437,433,428,424,420,416,412,408,404,400,396,392,388,385,381,377,374,370,367,363,360,357,354,350,347,344,341,338,335,332,329,326,323,320,318,315,312,310,307,304,302,299,297,294,292,289,287,285,282,280,278,275,273,
271,269,267,265,263,261,259],shg_table=[9,11,12,13,13,14,14,15,15,15,15,16,16,16,16,17,17,17,17,17,17,17,18,18,18,18,18,18,18,18,18,19,19,19,19,19,19,19,19,19,19,19,19,19,19,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,
23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24];function premultiplyAlpha(k){var v=k.data;k=k.width*k.height*4;for(var m=0;m<k;m+=4){var q=v[m+3]/255;v[m]*=q;v[m+1]*=q;v[m+2]*=q}}
function unpremultiplyAlpha(k){var v=k.data;k=k.width*k.height*4;for(var m=0;m<k;m+=4){var q=v[m+3];0!=q&&(q=255/q,v[m]*=q,v[m+1]*=q,v[m+2]*=q)}}function stackBlurImage(k,v,m,q){k=document.getElementById(k);var A=k.naturalWidth,y=k.naturalHeight,p=document.getElementById(v);p.style.width=A+"px";p.style.height=y+"px";p.width=A;p.height=y;p=p.getContext("2d");p.clearRect(0,0,A,y);p.drawImage(k,0,0);isNaN(m)||1>m||(q?stackBlurCanvasRGBA(v,0,0,A,y,m):stackBlurCanvasRGB(v,0,0,A,y,m))}
function stackBlurCanvasRGBA(k,v,m,q,A,y){var p;if(!(isNaN(y)||1>y)){y|=0;k=document.getElementById(k).getContext("2d");try{try{var I=k.getImageData(v,m,q,A)}catch(S){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalBrowserRead"),I=k.getImageData(v,m,q,A)}catch(T){throw alert("Cannot access local image"),Error("unable to access local image data: "+T);}}}catch(S){throw alert("Cannot access image"),Error("unable to access image data: "+S);}premultiplyAlpha(I);var l=I.data,z,e,a,u,c,
b,d,g,r,f,h,w,t,E,K;var C=y+y+1;var L=q-1,O=A-1,n=y+1,M=n*(n+1)/2,J=new BlurStack,x=J;for(e=1;e<C;e++)x=x.next=new BlurStack,e==n&&(p=x);x.next=J;var N=a=0;var F=mul_table[y],G=shg_table[y];for(z=0;z<A;z++){var H=g=r=f=u=c=b=d=0;var B=n*(h=l[a]);var P=n*(w=l[a+1]);var Q=n*(t=l[a+2]);var R=n*(E=l[a+3]);u+=M*h;c+=M*w;b+=M*t;d+=M*E;x=J;for(e=0;e<n;e++)x.r=h,x.g=w,x.b=t,x.a=E,x=x.next;for(e=1;e<n;e++){var D=a+((L<e?L:e)<<2);u+=(x.r=h=l[D])*(K=n-e);c+=(x.g=w=l[D+1])*K;b+=(x.b=t=l[D+2])*K;d+=(x.a=E=l[D+
3])*K;H+=h;g+=w;r+=t;f+=E;x=x.next}e=J;x=p;for(C=0;C<q;C++)l[a]=u*F>>G,l[a+1]=c*F>>G,l[a+2]=b*F>>G,l[a+3]=d*F>>G,u-=B,c-=P,b-=Q,d-=R,B-=e.r,P-=e.g,Q-=e.b,R-=e.a,D=N+((D=C+y+1)<L?D:L)<<2,H+=e.r=l[D],g+=e.g=l[D+1],r+=e.b=l[D+2],f+=e.a=l[D+3],u+=H,c+=g,b+=r,d+=f,e=e.next,B+=h=x.r,P+=w=x.g,Q+=t=x.b,R+=E=x.a,H-=h,g-=w,r-=t,f-=E,x=x.next,a+=4;N+=q}for(C=0;C<q;C++){g=r=f=H=c=b=d=u=0;a=C<<2;B=n*(h=l[a]);P=n*(w=l[a+1]);Q=n*(t=l[a+2]);R=n*(E=l[a+3]);u+=M*h;c+=M*w;b+=M*t;d+=M*E;x=J;for(e=0;e<n;e++)x.r=h,x.g=
w,x.b=t,x.a=E,x=x.next;D=q;for(e=1;e<=y;e++)a=D+C<<2,u+=(x.r=h=l[a])*(K=n-e),c+=(x.g=w=l[a+1])*K,b+=(x.b=t=l[a+2])*K,d+=(x.a=E=l[a+3])*K,H+=h,g+=w,r+=t,f+=E,x=x.next,e<O&&(D+=q);a=C;e=J;x=p;for(z=0;z<A;z++)D=a<<2,l[D]=u*F>>G,l[D+1]=c*F>>G,l[D+2]=b*F>>G,l[D+3]=d*F>>G,u-=B,c-=P,b-=Q,d-=R,B-=e.r,P-=e.g,Q-=e.b,R-=e.a,D=C+((D=z+n)<O?D:O)*q<<2,u+=H+=e.r=l[D],c+=g+=e.g=l[D+1],b+=r+=e.b=l[D+2],d+=f+=e.a=l[D+3],e=e.next,B+=h=x.r,P+=w=x.g,Q+=t=x.b,R+=E=x.a,H-=h,g-=w,r-=t,f-=E,x=x.next,a+=q}unpremultiplyAlpha(I);
k.putImageData(I,v,m)}}
function stackBlurCanvasRGB(k,v,m,q,A,y){var p;if(!(isNaN(y)||1>y)){y|=0;k=document.getElementById(k).getContext("2d");try{try{var I=k.getImageData(v,m,q,A)}catch(P){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalBrowserRead"),I=k.getImageData(v,m,q,A)}catch(Q){throw alert("Cannot access local image"),Error("unable to access local image data: "+Q);}}}catch(P){throw alert("Cannot access image"),Error("unable to access image data: "+P);}var l=I.data,z,e,a,u,c,b,d,g,r,f,h,w;var t=y+
y+1;var E=q-1,K=A-1,C=y+1,L=C*(C+1)/2,O=new BlurStack,n=O;for(e=1;e<t;e++)n=n.next=new BlurStack,e==C&&(p=n);n.next=O;var M=a=0;var J=mul_table[y],x=shg_table[y];for(z=0;z<A;z++){var N=d=g=u=c=b=0;var F=C*(r=l[a]);var G=C*(f=l[a+1]);var H=C*(h=l[a+2]);u+=L*r;c+=L*f;b+=L*h;n=O;for(e=0;e<C;e++)n.r=r,n.g=f,n.b=h,n=n.next;for(e=1;e<C;e++){var B=a+((E<e?E:e)<<2);u+=(n.r=r=l[B])*(w=C-e);c+=(n.g=f=l[B+1])*w;b+=(n.b=h=l[B+2])*w;N+=r;d+=f;g+=h;n=n.next}e=O;n=p;for(t=0;t<q;t++)l[a]=u*J>>x,l[a+1]=c*J>>x,l[a+
2]=b*J>>x,u-=F,c-=G,b-=H,F-=e.r,G-=e.g,H-=e.b,B=M+((B=t+y+1)<E?B:E)<<2,N+=e.r=l[B],d+=e.g=l[B+1],g+=e.b=l[B+2],u+=N,c+=d,b+=g,e=e.next,F+=r=n.r,G+=f=n.g,H+=h=n.b,N-=r,d-=f,g-=h,n=n.next,a+=4;M+=q}for(t=0;t<q;t++){d=g=N=c=b=u=0;a=t<<2;F=C*(r=l[a]);G=C*(f=l[a+1]);H=C*(h=l[a+2]);u+=L*r;c+=L*f;b+=L*h;n=O;for(e=0;e<C;e++)n.r=r,n.g=f,n.b=h,n=n.next;B=q;for(e=1;e<=y;e++)a=B+t<<2,u+=(n.r=r=l[a])*(w=C-e),c+=(n.g=f=l[a+1])*w,b+=(n.b=h=l[a+2])*w,N+=r,d+=f,g+=h,n=n.next,e<K&&(B+=q);a=t;e=O;n=p;for(z=0;z<A;z++)B=
a<<2,l[B]=u*J>>x,l[B+1]=c*J>>x,l[B+2]=b*J>>x,u-=F,c-=G,b-=H,F-=e.r,G-=e.g,H-=e.b,B=t+((B=z+C)<K?B:K)*q<<2,u+=N+=e.r=l[B],c+=d+=e.g=l[B+1],b+=g+=e.b=l[B+2],e=e.next,F+=r=n.r,G+=f=n.g,H+=h=n.b,N-=r,d-=f,g-=h,n=n.next,a+=q}k.putImageData(I,v,m)}}function BlurStack(){this.a=this.b=this.g=this.r=0;this.next=null}
(function(k){var v=k.Uint8Array,m=(k=k.HTMLCanvasElement)&&k.prototype,q=/\s*;\s*base64\s*(?:;|$)/i,A="toDataURL",y;v&&(y=new v([62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,0,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51]));!k||m.toBlob&&m.toBlobHD||(m.toBlob||(m.toBlob=function(k,m){m||(m="image/png");if(this.mozGetAsFile)k(this.mozGetAsFile("canvas",m));else if(this.msToBlob&&
/^\s*image\/png\s*(?:$|;)/i.test(m))k(this.msToBlob());else{var l=Array.prototype.slice.call(arguments,1),p=this[A].apply(this,l),e=p.indexOf(","),l=p.substring(e+1),p=q.test(p.substring(0,e));if(Blob.fake){var a=new Blob;a.encoding=p?"base64":"URI";a.data=l;a.size=l.length}else if(v)if(p){a=Blob;for(var p=l.length,e=new v(p/4*3|0),u=0,c=0,b=[0,0],d=0,g=0,r,f;p--;)f=l.charCodeAt(u++),r=y[f-43],255!==r&&void 0!==r&&(b[1]=b[0],b[0]=f,g=g<<6|r,d++,4===d&&(e[c++]=g>>>16,61!==b[1]&&(e[c++]=g>>>8),61!==
b[0]&&(e[c++]=g),d=0));a=new a([e],{type:m})}else a=new Blob([decodeURIComponent(l)],{type:m});k(a)}}),m.toBlobHD=!m.toBlobHD&&m.toDataURLHD?function(){A="toDataURLHD";var k=this.toBlob();A="toDataURL";return k}:m.toBlob)})("undefined"!==typeof self&&self||"undefined"!==typeof window&&window||this.content||this);
var saveAs=saveAs||function(k){if(!("undefined"===typeof k||"undefined"!==typeof navigator&&/MSIE [1-9]\./.test(navigator.userAgent))){var v=k.document.createElementNS("http://www.w3.org/1999/xhtml","a"),m="download"in v,q=/constructor/i.test(k.HTMLElement)||k.safari,A=/CriOS\/[\d]+/.test(navigator.userAgent),y=function(e){(k.setImmediate||k.setTimeout)(function(){throw e;},0)},p=function(e){setTimeout(function(){"string"===typeof e?(k.URL||k.webkitURL||k).revokeObjectURL(e):e.remove()},4E4)},I=function(e){return/^\s*(?:text\/\S*|application\/xml|\S*\/\S*\+xml)\s*;.*charset\s*=\s*utf-8/i.test(e.type)?
new Blob([String.fromCharCode(65279),e],{type:e.type}):e},l=function(e,a,l){l||(e=I(e));var c=this,b="application/octet-stream"===e.type,d=function(){for(var a=["writestart","progress","write","writeend"],a=[].concat(a),b=a.length;b--;){var d=c["on"+a[b]];if("function"===typeof d)try{d.call(c,c)}catch(w){y(w)}}};c.readyState=c.INIT;if(m){var g=(k.URL||k.webkitURL||k).createObjectURL(e);setTimeout(function(){v.href=g;v.download=a;var b=new MouseEvent("click");v.dispatchEvent(b);d();p(g);c.readyState=
c.DONE})}else(function(){if((A||b&&q)&&k.FileReader){var a=new FileReader;a.onloadend=function(){var b=A?a.result:a.result.replace(/^data:[^;]*;/,"data:attachment/file;");k.open(b,"_blank")||(k.location.href=b);c.readyState=c.DONE;d()};a.readAsDataURL(e);c.readyState=c.INIT}else g||(g=(k.URL||k.webkitURL||k).createObjectURL(e)),b?k.location.href=g:k.open(g,"_blank")||(k.location.href=g),c.readyState=c.DONE,d(),p(g)})()},z=l.prototype;if("undefined"!==typeof navigator&&navigator.msSaveOrOpenBlob)return function(e,
a,l){a=a||e.name||"download";l||(e=I(e));return navigator.msSaveOrOpenBlob(e,a)};z.abort=function(){};z.readyState=z.INIT=0;z.WRITING=1;z.DONE=2;z.error=z.onwritestart=z.onprogress=z.onwrite=z.onabort=z.onerror=z.onwriteend=null;return function(e,a,k){return new l(e,a||e.name||"download",k)}}}("undefined"!==typeof self&&self||"undefined"!==typeof window&&window||this.content);
"undefined"!==typeof module&&module.exports?module.exports.saveAs=saveAs:"undefined"!==typeof define&&null!==define&&null!==define.amd&&define("FileSaver.js",function(){return saveAs});
function svgToPNG(k,v){null==v&&(v="structure.png");var m=window.URL||window.webkitURL||window,q=$("<div>").append($("[id^="+k+"] svg:eq(0)").clone()).html(),q=q.replace('xmlns="http://www.w3.org/2000/svg" xmlns:NS1="" NS1:xmlns:xlink="http://www.w3.org/1999/xlink"',""),q=new Blob([q],{type:"image/svg+xml"}),m=m.createObjectURL(q);$("body").append('<canvas display="none" id="tmpcanvas"></canvas>');canvg("tmpcanvas",m,{renderCallback:function(){var k=document.getElementById("tmpcanvas");k.toBlob(function(k){saveAs(k,
v)});k.parentNode.removeChild(k)}})};